### ISSUE TITLE
Confirm time to run through design prototype

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/tempo#1]
@laurajtempo - please let me know if you'd like to meet on either Friday or next Wednesday.

**Comment by laurajtempo** [comment]
@thejoefriel Happy to go with Wednesday either 10am or after 2pm?

**Comment by thejoefriel** [comment]
Hi @laurajtempo - 10am would be perfect. Shall I come to your office?

**Comment by thejoefriel** [comment]
Hi @laurajtempo sorry for the potential last minute change, but is there any chance you are free tomorrow instead? I've been asked to go to Bristol for a meeting on Wednesday. If you can't though that's fine, happy to stick with Wednesday as keen to show you the prototype before too much further code is written.

**Comment by thejoefriel** [comment]
Following chat, we're now meeting today (Tues) at 2pm.
