### ISSUE TITLE
Build & Present Stylescapes

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/tempo#10]
**This issue is to build Stylescapes for the Tempo product** 

**Current reference points initially provided by Tempo
[Landscaping Feb 2020.docx](https://github.com/yalla-coop/tempo/files/4236929/Landscaping.Feb.2020.docx)
**

**Comment by JudeLuckett** [comment]
Monzo:
I love the look of Monzo in terms of listing activity and then categorising/saving etc. In future I wonder if people might like to save/donate/allocate to others in the same way as Pots? I also like the way you can find further info easily but it's not in your face. AND the nice white layout!

Instagram: I was wondering if we might like to slightly rip off their colour scheme in terms of pink and yellow and purple as they are all in our colours and nice and friendly!

Too Good to Go - the listings by type are interesting (thinking about engagement) - you could have Near You, Limited Offer, Your Favourites, Popular? They then also have 'Discover/List/Map/Favourites at the bottom for easy filtering. 

OLIO - has a call to action to spread the word at the top of the home page; leads to an email to volunteer.

**Comment by JudeLuckett** [comment]
Class Pass: booking
Calm: landing page. Onboarding asks you about your personal goals as soon as you open it. Asks for name, email and password to set up.
Headspace - on boarding
Ancestry: easy to use, intuitive. Pop up consent screen is 2 questions - one agreeing to terms, 1 to marketing. Jude has screenshot
Down Dog: yoga at home app

**Comment by JonnyBuck16** [comment]
https://volhours.com/

It’s an example of a system where Volunteers log their own hours and the group lead just approves or declines, it’s being used across Wales and our contact said uptake had been great!

A few further pieces of information on it, around on-boarding and on-going management too.

https://irp-cdn.multiscreensite.com/bd6fed78/files/uploaded/VolHours%20App%20Support.pdf

https://www.britishcycling.org.uk/zuvvi/media/Step_by_Step_Guide-_VH_Launch_.pdf

**Comment by JudeLuckett** [comment]
https://www.changegrowlive.org/
I like the initial select what you are looking for dropdown

**Comment by thejoefriel** [comment]
This is all great @JudeLuckett @JonnyBuck16 , thanks! Definitely send across as much as this. 

@jema28 looping you in to make sure you see this for your work on stylescapes today / tomorrow

**Comment by JudeLuckett** [comment]
Example presentation
[TEMPO AND TIME CREDITS.pptx](https://github.com/yalla-coop/tempo/files/4306530/TEMPO.AND.TIME.CREDITS.pptx)

PPT template
[Tempo Time Credits Template.pptx](https://github.com/yalla-coop/tempo/files/4306536/Tempo.Time.Credits.Template.pptx)

Example presentation (made in InDesign so we only have PDF) [TEMPO Strategy deck_B.pdf](https://github.com/yalla-coop/tempo/files/4306548/TEMPO.Strategy.deck_B.pdf)

**Comment by JudeLuckett** [comment]
[Icons.zip](https://github.com/yalla-coop/tempo/files/4306610/Icons.zip)
Sample icon files

**Comment by JudeLuckett** [comment]
[OneDrive_2020-03-09 (1).zip](https://github.com/yalla-coop/tempo/files/4306636/OneDrive_2020-03-09.1.zip)
Category icons

**Comment by JudeLuckett** [comment]
[OneDrive_2020-03-09 (2).zip](https://github.com/yalla-coop/tempo/files/4306647/OneDrive_2020-03-09.2.zip)
Icons used in evaluation

**Comment by JudeLuckett** [comment]
[Categories Spend.zip](https://github.com/yalla-coop/tempo/files/4307635/Categories.Spend.zip)
[Categories Earn.zip](https://github.com/yalla-coop/tempo/files/4307636/Categories.Earn.zip)

More recent icon designs - flat
