### ISSUE TITLE
Spend activity dates and times not displaying correctly in Spend Venue Accept Time Credits flow

### ISSUE THREAD

**Issue by JonnyBuck16** [yalla-coop/tempo#1015]
Loom video here: https://www.loom.com/share/4a024e6a09ff4a17a2979cf7831fdc4d

The Spend activity is available on the 5th and 6th of August only. On the Spend Venue accept Time Credits page, the activity is shown as being on the 3rd of August (today's date) only.

**Comment by thejoefriel** [comment]
Just noting that following our call we agreed to hide the dates completely from the spend activity button on the accept time credits page
