### ISSUE TITLE
I receive an email saying my request has been approved and the Time Credits are now in my account

### ISSUE THREAD

**Issue by JonnyBuck16** [yalla-coop/tempo#103]
__Is there an associated User Story?__

#100 #101 #102 

__Is this part of a User Journey?__

#99 

---

### Acceptance Criteria:
- [ ] User receives an email (Tempo to provide copy) 
- [ ] Link to Tempo platform
- [ ] BONUS: Celebratory tone

**Comment by thejoefriel** [comment]
This is now covered in the emails issue #180
