### ISSUE TITLE
I receive an email saying my request has been partially approved, the reason why, how many Time Credits I have been given, the Network Manager's email to discuss personally

### ISSUE THREAD

**Issue by JonnyBuck16** [yalla-coop/tempo#104]
__Is there an associated User Story?__

#100 #101 #102 
__Is this part of a User Journey?__

#99 
---

### Acceptance Criteria:
- [ ] User receives email (Tempo to provide copy)
- [ ] In the email there is a link to buy more if I need to

Notes
- [ ] If User Clicks buy more, they enter buy Time Credits Journey #106

**Comment by thejoefriel** [comment]
Have put this into the emails issue #180
