### ISSUE TITLE
I receive an email saying my request has been rejected, the reason why, the Network Manager's email to discuss personally

### ISSUE THREAD

**Issue by JonnyBuck16** [yalla-coop/tempo#105]
__Is there an associated User Story?__

#100 #101 #102 

__Is this part of a User Journey?__

#99 
---

### Acceptance Criteria:
- [ ] User receives email (Tempo to provide copy)

Notes

- [ ] If User Clicks buy more, they enter buy Time Credits Journey #106

**Comment by thejoefriel** [comment]
Have put into issue #180
