### ISSUE TITLE
Agree database schema

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/tempo#11]
Please try building models and paste in here along with your thinking

**Comment by thejoefriel** [comment]
I've put together the initial schema [here](https://drive.google.com/file/d/18FQi-dXJT0Q87QsJ3wRtxrMEQfdktomr/view?usp=sharing)

![image](https://user-images.githubusercontent.com/19708921/53242178-e6b58f80-369b-11e9-8072-d3f3fe17e93d.png)

**Comment by thejoefriel** [comment]
Here's how it would look in model/schema form:

```
// MEMBERS
{
  name: {
    type: String,
    required: true,
  },
  email: {
    type: String,
    required: true,
  },
  password: {
    type: String,
    required: true,
  },
}

// TIME CREDIT CARD
{
  qrCode: {
    type: String,
    required: true,
  },
  active: {
    type: Boolean,
    default: false,
  },
  member: { 
    type: Schema.Types.ObjectId, 
    ref: 'Member' }
}

// PARTNERS
{
  name: {
    type: String,
    required: true,
  },
  type: {
    type: String,
    required: true,
    enum: ["give", "spend"],
  },
}

// VOLUNTEER LIST
{
  member: { 
    type: Schema.Types.ObjectId, 
    ref: 'Member' 
    },
  partner: { 
    type: Schema.Types.ObjectId, 
    ref: 'Partner' 
    },
}

//TRANSACTIONS
{
  date: {
    type: Date,
    required: true,
  },
  credits: {
    type: Number,
    required: true,
  },
  activites: {
    type: Array, 
    required: true,
  }
  timeCreditCard: { 
    type: Schema.Types.ObjectId, 
    ref: 'TimeCreditCard' 
  },
  partner: { 
    type: Schema.Types.ObjectId, 
    ref: 'Partner' 
  },
}
```

**Comment by dupreesi** [comment]
Looks good to me!

**Comment by RamyAlshurafa** [comment]
Hey @thejoefriel 
here are my thoughts about the schema
* we will have 2 tables only
   - first: for `users`:
     it will include all the user types with a role column.
   - second: for `transactions`
     it will store all the transactions occurred and will contain the users that involved as from (sender) and to (receiver) 
```js
// First table
users: {

  name: {
    type: String,
    required: true,
  },
  email: {
    type: String,
    required: true,
  },
  password: {
    type: String,
    required: true,
  },
  role: {
    type: String,
    required: true,
    enum: ["Tempo", "Charity", "SpendPartner", "Volunteer"],
  },
  cards:{
    type: Number, // the member's account of credits time 
    default: 0,
  }
}

// Second table
transactions :{
  date: {
    type: Date,
    default: date.now()
  },
  CreditesTimeNumber: {
    type: Number,
    required: true,
  },
  from: {
    type: Schema.Types.ObjectId, 
    ref: 'user' 
  },
  to: {
    type: Schema.Types.ObjectId, 
    ref: 'user' 
  },
  activities: [String] // Array of strings
}
```

**Comment by thejoefriel** [comment]
Hi @RamyAlshurafa yeah this looks good and keeps things simpler in terms of the number of models we create

**Comment by thejoefriel** [comment]
My only issue is surely it would be a good idea to store the QR code image as well? That way they can get it again if they wish to print it again? Also, I had active just in case they have a time credit card and lost it, so they wish to expire that one and get a new one. This way we could still store a record of deactivated cards

**Comment by RamyAlshurafa** [comment]
aha, Do we need to make QR for Time Credits? I think we agreed to make the QR for volunteers, and keep the Time Credits virtual, so eg. when Charity need to give the volunteer 5 Time Credits it will scan the volunteer card, not the Time Credits

**Comment by thejoefriel** [comment]
Yes sorry @RamyAlshurafa for the confusion, that's what I'm referring to. The QR code is for the 'Time Credit Card' which each volunteer has. So we'd ideally store the QR code for each card?

**Comment by thejoefriel** [comment]
So each volunteer would have a Time Credit Card which is what they would scan as you say. I think though it would be a good idea to store the QR code image, in case we need to print their card again, and also to store whether it's active or not, in order that cards can be deactivated if someone loses one etc

**Comment by thejoefriel** [comment]
What do you think?

**Comment by RamyAlshurafa** [comment]
Maybe I misunderstood the process

**Comment by RamyAlshurafa** [comment]
aha, good
so maybe we need a third table to link the cards with volunteer and store the card status and code?
```js
Cards : {
  volunteer: {
     type: Schema.Types.ObjectId, 
    ref: 'user'
  },
  qrCode: {
    type: String,
    required: true,
  },
  active: {
    type: Boolean,
    default: true,
  },
}
```

**Comment by thejoefriel** [comment]
Yeah that's what I was thinking

**Comment by thejoefriel** [comment]
Apart from that, I'm happy for you to go ahead with building the database :)

**Comment by RamyAlshurafa** [comment]
ah cool :)
Actually, I copied it from your comment
