### ISSUE TITLE
MVP Content for Customers

### ISSUE THREAD

**Issue by JonnyBuck16** [yalla-coop/tempo#116]
[MVP Content for Customers (2).docx](https://github.com/yalla-coop/tempo/files/4324173/MVP.Content.for.Customers.2.docx)

Hi both, feel free to ask questions on this!

**Comment by JonnyBuck16** [comment]
@jema28 just re-uploaded the document here with request/buy more Time Credits content. Sorry for the delay!

**Comment by jema28** [comment]
@JonnyBuck16 Perfect, thanks and no worries!
