### ISSUE TITLE
Set up communication channels

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/tempo#12]
### Acceptance Criteria:
- [x] Brief Yalla team that we'll try Teams rather than Slack for day to day client communication
- [x] Add Yalla team to Teams communication

**Comment by thejoefriel** [comment]
Hi @JudeLuckett @JonnyBuck16 are you able please to add the following onto Teams:

simon@yallacooperative.com
jem@yallacooperative.com
ramy@yallacooperative.com
ahmed.shatat87@gmail.com
fadeomar2015@gmail.com

**Comment by JonnyBuck16** [comment]
Just added you all - let me know if there are any problems!
