### ISSUE TITLE
Daily Stand Up Log

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/tempo#12]
In this issue, at the end of each working day, please add a comment answering the following questions:

### Am I facing any blockers?

**Comment by thejoefriel** [comment]
### Date:
Thu 21 Feb 2019

### What issue(s) did I work on today?
#2 and #10 

### What issue do I plan to work on tomorrow?
Finish #10 and also put user stories into issues

### Am I facing any blockers?
No

**Comment by RamyAlshurafa** [comment]
### Date:
Thu 21 Feb 2019

### What issue(s) did I work on today?
#2, #10 and #3 

### What issue do I plan to work on tomorrow?
well see
### Am I facing any blockers?
No

**Comment by dupreesi** [comment]
### Date:
Thu 21 Feb 2019

### What issue(s) did I work on today?
#7, #6 

### What issue do I plan to work on tomorrow?
finishing deployment #9, #8  

### Am I facing any blockers?
No

**Comment by thejoefriel** [comment]
### Date:
Fri 22 Feb 2019

### What issue(s) did I work on today?
#8 #5 #10 

### What issue do I plan to work on tomorrow?
Weekend tomorrow, so not sure what I'll pick up on Monday

### Am I facing any blockers?
No

**Comment by dupreesi** [comment]
### Date:
Fri 22 Feb 2019

### What issue(s) did I work on today?
#7, #8, #9 #6 
### What issue do I plan to work on tomorrow?
same as joe

### Am I facing any blockers?
No

**Comment by RamyAlshurafa** [comment]
### Date:
Tue 26 Feb 2019

### What issue(s) did I work on today?
#29, #28
### What issue do I plan to work on tomorrow?
#19 
### Am I facing any blockers?
No

**Comment by thejoefriel** [comment]
### Date:
Tue 26 Feb 2019

### What issue(s) did I work on today?
#19 
Had meeting with Laura - summarised here #44 

### What issue do I plan to work on tomorrow?
#19 

### Am I facing any blockers?
No - only that I had a meeting with Laura to took some time out from coding on Tuesday, which I've summarised here #44

**Comment by dupreesi** [comment]
### Date:
Thu 28th Feb 2019

### What issue(s) did I work on today?
#18

### What issue do I plan to work on tomorrow?
check error in app.test.js and create PR for #18
not sure what I'm gonna work on next yet...

### Am I facing any blockers?
No

**Comment by RamyAlshurafa** [comment]
### Date:
Thu 28th Feb 2019

### What issue(s) did I work on today?
#24, #49 

### What issue do I plan to work on tomorrow?
#25 

### Am I facing any blockers?
yes, #24 has an error in `App.test.js` and Travis fails.

**Comment by dupreesi** [comment]
### Date:
Fri 1st March 2019

### What issue(s) did I work on today?
#18 

### What issue do I plan to work on tomorrow?
/

### Am I facing any blockers?
yes, still the  error in `App.test.js`. couldnt find a solution for it so removed it for now

**Comment by thejoefriel** [comment]
Date:
Fri 1st March 2019

What issue(s) did I work on today?
#30 #22 #26 #23 #33 

What issue do I plan to work on tomorrow?
#31 

Am I facing any blockers?
No

**Comment by RamyAlshurafa** [comment]
Date:
Sun 3rd March 2019

What issue(s) did I work on today?
#25, #63, #21 
What issue do I plan to work on tomorrow?
for the next working day continue working on #21 
Am I facing any blockers?
No

**Comment by RamyAlshurafa** [comment]
Date:
Wed 6th March 2019

What issue(s) did I work on today?
#69 & #71

What issue do I plan to work on tomorrow?
finish #71, then make the front for #21 to be completed

Am I facing any blockers?
No

**Comment by thejoefriel** [comment]
Wed 6th March 2019

What issue(s) did I work on today?
#56 #70 #34

What issue do I plan to work on tomorrow?
#31 and #34

Am I facing any blockers?
No

**Comment by dupreesi** [comment]
Wed 6th March 2019

What issue(s) did I work on today?
#32 

What issue do I plan to work on tomorrow?
#32 

Am I facing any blockers?
No

**Comment by RamyAlshurafa** [comment]
Date:
Thu 7th March 2019

What issue(s) did I work on today?
#71

What issue do I plan to work on tomorrow?
#21 and then will see

Am I facing any blockers?
No

**Comment by dupreesi** [comment]
Date:
FRI 8th March 2019

What issue(s) did I work on today?
#32 

What issue do I plan to work on tomorrow?
#45 

Am I facing any blockers?
No

**Comment by thejoefriel** [comment]
Date:
FRI 8th March 2019

What issue(s) did I work on today?
#31

What issue do I plan to work on tomorrow (monday)?
#34 then #68 

Am I facing any blockers?
No

**Comment by RamyAlshurafa** [comment]
Date:
Sun 10th March 2019

What issue(s) did I work on today?
#72 , #78 

What issue do I plan to work on tomorrow?
fix #91 , #92 , #77 
Am I facing any blockers?
No
