### ISSUE TITLE
fix responsiveness in Transactions page

### ISSUE THREAD

**Issue by RamyAlshurafa** [yalla-coop/tempo#120]
**transaction ammount and arrow will go behined the navbar in large view**

![ffffffffffffffffff](https://user-images.githubusercontent.com/34629478/54232882-694fa300-4514-11e9-8f08-b450b0012878.png)

![fffffff](https://user-images.githubusercontent.com/34629478/54232820-3e654f00-4514-11e9-86f3-af7417a0e1bd.png)

**Comment by thejoefriel** [comment]
@RamyAlshurafa I think this may be fixed in the PR I pushed up

**Comment by RamyAlshurafa** [comment]
Yeah fixed :+1: and merged
Thank you :)
