### ISSUE TITLE
Build Initial Low Res Wireframes (Pre User Testing)

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/tempo#124]
**Here's the link to the low res wireframes**
https://www.figma.com/file/PWG8VdfaELI4j5H2XAcqPH/Tempo?node-id=154%3A0

- [x] Members low res
- [x] Members client feedback & changes made
- [x] Customers low res
- [x] Customers client feedback & changes made
- [x] Spend Partner low res
- [x] Spend Partner client feedback & changes made
- [x] Tempo low res
- [x] Tempo client feedback & changes made

**Comment by thejoefriel** [comment]
Hey @JudeLuckett @JonnyBuck16 @harrietepugh - the member low res screens are done (except for the earn opportunity profile which I think we're getting content from you on?) and ready for feedback. 

I've sent you email invites to view the prototype. For members, go to Member Low res. Let me know if any issues viewing and making comments. 

Also if you want to view it as a prototype, here's the link for that: https://www.figma.com/proto/PWG8VdfaELI4j5H2XAcqPH/Tempo?node-id=187%3A119&scaling=scale-down

You can also do this in Figma. I've recorded a gif for you showing how to do this :) https://recordit.co/qXux5hh1Qh

**Comment by jema28** [comment]
Hey @JudeLuckett @JonnyBuck16 @harrietepugh, the Customer low res screens are ready for your feedback. They're in the Customer Low Res tab. 

Here's the prototype link also: https://www.figma.com/proto/PWG8VdfaELI4j5H2XAcqPH/Tempo?node-id=270%3A144&viewport=446%2C547%2C0.1589801013469696&scaling=scale-down

**Comment by jema28** [comment]
**Feedback checklist for 13/03:**
**Members**
- [ ] Sort Earn groups content 
- [ ] Decide the wording for main screen: dashboard or home?
- [ ] Add My Profile to menu (R2)
- [ ] Add a map section to Spend Partner profile (R2)
- [ ] Add a url with Tempo Membership just in case spend partner doesn't know it
- [ ] Gift or give your time credits - @harrietepugh we want 'give' throughout right?
- [ ] Shorten membership number so easier to remember (no need for it to be long!)
- [ ] Fix typos 

**Customer**

**Spend**

**Comment by JudeLuckett** [comment]
Also: adjust Welcome cards wording:

Earn Tempo Time Credits simply by giving your time in a way that works for you. Time Credits will be added to your account after you volunteer with an organisation or community group 

Spend Tempo Time Credits on fun activities with friends and family. Search for activities here in the app, then use your Tempo ID to access it with Time Credits in person

Can we try that and see if it fits? Realised we need a bit more instruction I think

**Comment by thejoefriel** [comment]
Hi @JudeLuckett @JonnyBuck16 @harrietepugh , Spend Partner wireframes and prototype are ready to review. 

Please note, you can't get to the unsuccessful screen via the prototype so you'll need to look at it via the wireframe

**Comment by JonnyBuck16** [comment]
Great - thanks @thejoefriel

**Comment by JudeLuckett** [comment]
Just gone through all these and added my notes. Thanks @thejoefriel @jema28 they look cool.

If you have any questions/issues over the weekend that need a reply so we're ready for testing, let me know on 07901979637?

Thanks
Jude

**Comment by jema28** [comment]
Hey @JudeLuckett, thanks for the feedback yesterday. We've finished going through 98% of the comments (a few of @JonnyBuck16's comments have become unattached - commented on these in figma)/changed the customer onboarding designs a little to make them more desktop friendly. Will double-check the prototypes tomorrow but everything should now be ready for testing :)

**Comment by thejoefriel** [comment]
Hey @JudeLuckett @JonnyBuck16 @harrietepugh - I'm still finishing up Tempo staff pages, but I think there's enough in there currently for you to add your comments if you started wanting to look through?
