### ISSUE TITLE
Agree Tech Stack

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/tempo#127]
This issue is to put together our recommend technology approach for the product. The final result of this issue should be a written document which we can store here for reference, as well as then putting into the repo's readme.

- [x] Front end 
- [x] Back end 
- [x] Frameworks / Libraries (e.g. antd)
- [x] Database
- [x] Third Party apps
- [x] Testing
- [x] Key npm packages we know we'll likely use (e.g. bcryptjs)

For each technology we need to include:
- Name
- 1-line description
- Why we recommend using it

@JudeLuckett if you feel you need more information beyond this please just let us know and I'll add it in.

**Comment by JudeLuckett** [comment]
Kelly's thoughts on this when I spoke to her were that we should have more than one option for technology - particularly the key ones - even if there is a preferred option. I think that would also be helpful for Board in terms of thoroughness etc. Let me know if you want me to discuss?

**Comment by fadeomar** [comment]
## Tempo :tech stack : -
### For back end : 
  - **Express** : 
     * Fast, unopinionated, minimalist web framework for Node.js.
     * **why** : ExpressJS is NodeJS framework that can help us in creating server-side web applications faster and smarter.
     
  - **mocha**: 
    * Mocha is a feature-rich JavaScript test framework running on Node.js, making asynchronous testing very well. 
    * **why** : Mocha tests run serially, allowing for flexible and accurate reporting, while mapping uncaught exceptions to the correct test cases. Hosted on GitHub.
    
  - **JSON Web Token** : 
    * It's an internet standard for creating JSON-based access tokens that assert some number of claims.
    * using it through the Authorization process 
    * using it to generate a token through verification process.
    * it's a good way of securely transmitting information between parties.
    
  - **Yup** : 
    * using yop javaScript schema for validation according to the specific schema
    * we can use it in the ***Front-end*** and in the ***back-end***
    
  - **bcryptjs** : 
    * to help us hashing the passwords .
  
  - **ESLint** : 
    * ESLint is a tool for identifying and reporting on patterns found in ECMAScript/JavaScript code.
    * we can use it in the ***Front-end*** and in the ***back-end***

  - **dotenv** : 
    *  to storing configuration in the environment separate from code .
    ----
### For fornt end : 
  - **React** : 
    * A JavaScript library for building user interfaces
    *  It hides its complex rendering engine implementation and exposes a simple component API.
    *  every UI is composed of components, so there is no mismatch of multiple types to worry about. Since there is only one common object, it makes it easy to nest components inside components and encourages the principle of single responsibility for each component.
    
  - **Redux** : ??
    * A Predictable State Container for JS Apps.
    * **why** : It’s clear that state management gets messy as the app gets complex. This is why you need a state management tool like Redux that makes it easier to maintain these states.
    
  - **material-Ui** : 
    * React components for faster and easier web development.
    * Build your own design system, or start with Material Design.
    * Material UI is a very solid and stable set of react components that not only look good, but also are easy to customize .
    * Very well documentations are organized and easily to navigable .
    
    
  - **cypress** : 
    * Fast, easy and reliable testing for the functinal , components and logic that runs in a browser.
    * Optimizing the front-end performance .
    * To conduct various kinds of functionality in the developmnet stage .

  - **S3** : 
    * using Amazon S3 for hosting and store images.
    * Hosting Images on Amazon S3 gives you the ability to store a large amount of data with a very low cost.
    * Data stored in Amazon is secure by default because only owner and bucket have access to Amazon S3 resources
    * src for pricing : [s3 Pricing](https://aws.amazon.com/ar/s3/pricing/) 


---

### For RDBMS : 
Stands for "Relational Database Management System. the RDBMS is a DBMS designed specifically for relational databases. A relational database refers to a database that stores data in a structured format, using rows and columns. This makes it easy to locate and access specific values within the database. It is "relational" because the values within each table are related to each other. Tables may also be related to other tables. The relational structure makes it possible to run queries across multiple tables at once.

  * ### PostgrSQl
    - **why**: Postgres bills itself as “the most advanced open-source relational database in the world.” It was created with the goal of being highly extensible and standards compliant. PostgreSQL is an object-relational database, meaning that although it’s primarily a relational database it also includes features, and there is many resons to chose it .
    
            
    * **Advantages**:
      1. ***Supported Data Types***:
        supports numeric, string,date and time data types, data types for geometric shapes, network addresses, bit strings, text searches, and JSON.
          * Numeric types:
            - (bigint, bigserial, double precision	, integer, numeric or decimal, etc...)
          * Character types: 
            - (character, character varying or varchar, text) 
          * Date and time types:
            - (date, interval, time or time without time zone, time with time zone, etc...)
          * Other data types:
            - (json, boolean, uuid, etc...)
            
      2. SQL compliance: More so than RDBMS's, PostgreSQL aims to closely adhere to SQL standards.
      3. Open-source and community-driven:  A fully open-source project, PostgreSQL’s source code is developed by a large and devoted community.
      4. Popularity :As one of the world’s most popular database systems
    * **Disadvantages**:
      1. Memory performance: For every new client connection, PostgreSQL forks a new process. Each new process is allocated about 10MB of memory, which can add up quickly for databases with lots of connections. Accordingly, for simple read-heavy operations, PostgreSQL is typically less performant than other RDBMSs.
    * **Alternatives**: 
    there is many DBRMS alternatives , and the first of the two open-source relational databases after the PostgrSQL is : 
      - ### **SQLite**
          * SQLite is a software library that provides a relational database management system. The lite in SQLite means light weight in terms of setup, database administration, and required resource.

            SQLite has the following noticeable features: self-contained, serverless, zero-configuration, transactional. 
            src: [SQLite](https://www.sqlite.org/about.html)
        * #### Advantages of SQLite:
            1. **User-friendly:** SQLite is sometimes described as a “zero-configuration” database that’s ready for use out of the box.
            
            2. **Portable:** Unlike other database management systems, which typically store data as a large batch of separate files,Portable: Unlike other database management systems, which typically store data as a large batch of separate files.
            
            3. **Small footprint:** As its name implies, the SQLite library is very lightweight. Although the space it uses varies depending on the system where it’s installed, it can take up less than 600KiB of space. Additionally, it’s fully self-contained, meaning there aren’t any external dependencies you have to install on your system for SQLite to work.
        * #### Disadvantages of SQLite:
            1. **Limited concurrency:** Although multiple processes can access and query an SQLite database at the same time, only one process can make changes to the database at any given time. 
            2. **No user management:** Database systems often come with support for users, or managed connections with predefined access privileges to the database and tables. 
            3. **Security:** A database engine that uses a server can, in some instances, provide better protection from bugs in the client application than a serverless database like SQLite. 
      - ### **MySql**
        * MySQL is a relational database management system, used for a wide range of purposes, including data warehousing, e-commerce, and logging applications. was designed for speed and reliability, at the expense of full adherence to standard SQL.
        * #### Advantages of MySql:
          1. **Security:** MySQL comes installed with a script that helps you to improve the security of your database by setting the installation’s password security level, defining a password for the root user, removing anonymous accounts, and removing test databases that are, by default, accessible to all users.
          2. **Replication:** MySQL supports a number of different types of replication, which is the practice of sharing information across two or more hosts to help improve reliability, availability, and fault-tolerance. This is helpful for setting up a database backup solution or horizontally scaling one’s database.
          
        * #### Disadvantages of MySql:
            1. **Known limitations:** Because MySQL was designed for speed and ease of use rather than full SQL compliance, it comes with certain functional limitations.
            
            2. **Licensing and proprietary features:** not all the features are free.
            
            3. **Slowed development:**: there have been complaints from users that the development process for the DBMS has slowed down significantly, as the community no longer has the agency to quickly react to problems and implement changes.

**Comment by JudeLuckett** [comment]
Thanks! Can we arrange a time (ahead of Board on Friday, ideally tomorrow so I can share with them ahead of the call) for you to talk me through and pick up any questions?

**Comment by JudeLuckett** [comment]
Also - I can think about this if not - any chance of a visual depiction? Ie a system architecture map?

**Comment by thejoefriel** [comment]
Hi @JudeLuckett here is the full document outlining our tech stack, primary recommendations (and alternatives), and also including our recommendations for external services and deployment too! 

https://www.notion.so/Tech-Stack-External-Services-Deployment-Recommendation-f1c95727e87c470295231d34168d9d6e

**Comment by thejoefriel** [comment]
In terms of call, I can chat tomorrow, anytime in the afternoon. When is best for you @JudeLuckett ?

**Comment by JudeLuckett** [comment]
Hi @thejoefriel I notice there is a 'ADD MORE' comment in the Front End section. I think it's fine to just say we are all experts in this and therefore recommend it - but can you update so when I share with Board it looks complete? thanks :0

**Comment by thejoefriel** [comment]
Sorry about that @JudeLuckett I had a paragraph from the team I was meaning to put in there. I've done that now

**Comment by thejoefriel** [comment]
Hi @JudeLuckett here's the system architecture for you: https://whimsical.com/7egj1LtRoAmz54RukaLMbG
