### ISSUE TITLE
Hi Res User Testing

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/tempo#129]
## Purpose of this issue:
- [x] Store the Hi Res user testing sessions
- [x] Store who is assigned to work on them and whether remote or in person
- [x] Link to the Figma prototype
- [x] Link to User Testing script(s)
- [x] Link to User Testing Feedback Form (to be filled in by one of our team)
- [ ] Discuss which elements we feel are important and require wireframe changes via comments in this issue

## Roles
Every User Testing session must be attended by min. 2 people (1 from Tempo / 1 from Yalla)
- Tempo: Leads the interview with the user
- Yalla: Documents the feedback throughout the session 

## Documentation
**Scripts**
https://www.notion.so/User-Testing-8f045c9ac9b749c5b9266f8711113252

**Where to store feedback**
https://www.notion.so/Tempo-Yalla-Shared-Docs-40a5fc4a0c894fbda51dbb03eec7d6bd

### Desktop
**Customer**
https://www.figma.com/proto/PWG8VdfaELI4j5H2XAcqPH/Tempo?node-id=1708%3A39924&scaling=scale-down

**Member**
https://www.figma.com/proto/PWG8VdfaELI4j5H2XAcqPH/Tempo?node-id=1887%3A68981&scaling=min-zoom

**Spend Partner**
https://www.figma.com/proto/PWG8VdfaELI4j5H2XAcqPH/Tempo?node-id=1273%3A37813&scaling=min-zoom

**Tempo Staff**
https://www.figma.com/proto/PWG8VdfaELI4j5H2XAcqPH/Tempo?node-id=1273%3A30276&scaling=min-zoom

### Mobile

**Customer**
https://www.figma.com/proto/PWG8VdfaELI4j5H2XAcqPH/Tempo?node-id=1176%3A107&scaling=scale-down

**Member**
https://www.figma.com/proto/PWG8VdfaELI4j5H2XAcqPH/Tempo?node-id=1094%3A29769&scaling=scale-down

**Spend Partner**
https://www.figma.com/proto/PWG8VdfaELI4j5H2XAcqPH/Tempo?node-id=1394%3A1769&scaling=scale-down

### Monday 6th April
**Member Testing**
- Location: Remote
- Users: 4
- 11.00-11.30 Linda 
- 12.00-12.30 Cindy
- 14.00-14.30 Alison
- 15.00-15.30 Sam
- Assigned: @harrietepugh (in person) & @jema28  

**Customer Testing**
- Location: Remote
- Users: 1
- 14:00-15:00 Alan 
- Assigned @JonnyBuck16 & @dupreesi 

**Spend Partner Testing**
- Location: Remote
- Users: 2
- 11:00 - 12:00 Jasmine / Assigned @JonnyBuck16 & @dupreesi  

### Tues 7th April 
**Customer Testing**
- Location: Remote 
- Users: 2
- 12:00 - 13:00 Marie
- 14:00 - 15:00 Yvonne
- Assigned: @JonnyBuck16 & @thejoefriel 

**Spend Partner Testing**
- Location: Remote
- Users: 3
- 11:00 - 12:00 Claire
- 15:00 - 16:00 Taz
- 16:00 - 15:30 Chiara
 - Assigned: @JonnyBuck16 & @thejoefriel 

**Tempo Staff Testing**
- Location: Remote
- Users: 4
- 10.00-10.30 Hannah
- 12:00 - 13:00 Rachel
- 14.00-15.00 Roisin
- 15.30-16.00 Anne-Marie
- Assigned: @harrietepugh & @jema28

### Weds 8th April
**Member Testing**
- Location: Remote
- Users: 1
- 16.30-17.00 Abby
- Assigned: @harrietepugh (in person) & @jema28

### Weds 8th April
**Member Testing**
- Location: Remote
- Users: 4
- 10.00-10.30 Ray
- 11.00-11.30 Marcelle
- 12.00-12.30 Amy's Mum
- 14.00-14.30 Lovely Linda
- Assigned: @harrietepugh (in person) & @jema28

**Customer Testing**
- Location: Remote
- Users: 2
- 14:30 - 15:30 Meryl
- 16:00 - 17:00 Pam 
- Assigned @JonnyBuck16  & @jema28

**Spend Partner Testing**
- Location: Remote
- Users: 2
- 10:00 - 11:00 Kelsey
- 11:00 - 12:00 Jonathan 
- Assigned @JonnyBuck16  & @dupreesi 

### Thurs 9th April
**Spend Partner Testing**
- Location: Remote
- Users: 1
- 15:00 - 16:00 Zoe
- Assigned @JonnyBuck16 & @jema28 

**Customer Testing**
- Location: Remote
- Users: 2
- 10:00 - 11:00 Paulette
- 11:00 - 12:00 Mark
- Assigned @JonnyBuck16 @jema28

**Comment by JonnyBuck16** [comment]
Hey @thejoefriel, had 2 more confirmations for Thursday this week today, so have just added these here (Zoe and Mark) just checking the times work for you guys?
