### ISSUE TITLE
Tasks Ahead of Sprint Planning Session on 27/03

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/tempo#140]
This outlines what ideally you will do internally ahead of our meeting tomorrow:

- [x] Review the issues in github and make sure they are all in there and acceptance criteria up to date 
- [x] Internally discuss your goals for release 1 and what you feel are things you absolutely must have
 - [x] Ideally send me these so I can have a think ahead of our meeting

Thanks!

**Comment by harrietepugh** [comment]
@thejoefriel here is the R1 features as agreed previously. Go to the tabs to see these updated for discussion tomorrow and what might be needed for a national offer. Cheers![Release Plan Features V1.xlsx](https://github.com/yalla-coop/tempo/files/4388576/Release.Plan.Features.V1.xlsx)

**Comment by JudeLuckett** [comment]
Latest spreadsheet with bonus features in red
[Release Plan Features V1.xlsx](https://github.com/yalla-coop/tempo/files/4394673/Release.Plan.Features.V1.xlsx)

**Comment by thejoefriel** [comment]
Have added these into the main resources issue #15 for reference
