### ISSUE TITLE
I go to the url I have been given and see a log in page with email, password fields 

### ISSUE THREAD

**Issue by JonnyBuck16** [yalla-coop/tempo#143]
__Is this part of a User Journey?__
#142 

### Acceptance Criteria:
- [ ] Tempo logo / banner (make sure this is evident throughout the entire journey)
- [ ] Email field (basic on blur validation to test it is a standard email)
- [ ] Password field
- [ ] Log In Button
- [ ] Accept Time Credits without logging in link

**Comment by thejoefriel** [comment]
This is a duplicate of #25
