### ISSUE TITLE
As a user, I can navigate the app using a menu

### ISSUE THREAD

**Issue by harrietepugh** [yalla-coop/tempo#146]
This outlines the common menu component that each user will see 

### Acceptance Criteria:
- [ ] Design in line with mobile and desktop wireframes

- [ ] Logged out users on main website
    - [ ] Log In

- [ ] Members
    - [ ] Home
   - [ ] Earn Time Credits
   - [ ] Spend Time Credits
   - [ ] Gift Time Credits
    - [ ] My Time Credits History
   - [ ] How Time Credits Work
    - [ ] Log Out

- [ ] Earn Groups
    - [ ] Give Out Time Credits
    - [ ] My Members
    - [ ] Invite a new Member
    - [ ] My Time Credits History
    - [ ] Get more Time Credits
    - [ ] Log out

- [ ] Spend Partners
    - [ ] Accept Time Credits
    - [ ] Insights

- [ ] Tempo Staff
    - [ ] Dashboard
    - [ ] Time Credit Requests
    - [ ] Earn Groups
    - [ ] Members
    - [ ] Spend Partners
    - [ ] Transactions

**Comment by thejoefriel** [comment]
Hey @harrietepugh @JonnyBuck16 - I've put a common menu issue here to cover the different user types. For now I've just listed mainly the ones we know we want to get in there for release 1 and we can then add to the menu more items relatively easily once we start adding more features.

**Comment by JonnyBuck16** [comment]
Can we add "Accept Time Credits" to the Customer menu for R1? Ta!

**Comment by thejoefriel** [comment]
I've left out for now @JonnyBuck16 just because we've put it in as bonus but will definitely put that in as soon as we get to it :)
