### ISSUE TITLE
Send across Tempo Logins

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/tempo#16]
Hi @JudeLuckett thinking ahead to when the team will start reviewing the existing tempo digital products to see if there's anything we can use, learn from etc, are you able please to add links to the products and the relevant log in information to the Admin Info spreadsheet in #15 please

**Comment by JudeLuckett** [comment]
Sure - @JonnyBuck16 is on this!

**Comment by JonnyBuck16** [comment]
All done!
