### ISSUE TITLE
I see a Page where I can approve, partially approve or reject a Time Credits Request and issue Time Credits

### ISSUE THREAD

**Issue by JonnyBuck16** [yalla-coop/tempo#178]
__Is there an associated User Story?__

 #177  #169

__Is this part of a User Journey?__

#173 #167

---

### Acceptance Criteria:
- [ ] Number of Time Credits (not an input)
- [ ] Text field to send them a message
- [ ] Helper text on the sort of thing they should say
- [ ] Render the correct view based on whether they have clicked the button to approve, partially approve or reject, or have selected to issue time credits to an Earn Group or member (this would default to the partially approve view) 
- [ ] If approve, show the amount that they requested
- [ ] Confirm Button
- [ ] Cancel button
- [ ] On confirm the recipient receives an email (#180 )

**Comment by thejoefriel** [comment]
Hey @JonnyBuck16 where we say number of credits isn't an input, are we giving tempo users pre-selected options to choose from?

**Comment by JonnyBuck16** [comment]
Sorry this was blindly copied and pasted out of whimsical. I would've thought we would want to staff to send any number of Time credits, rather than be limited by pre-selected amounts.

@harrietepugh do you agree?

**Comment by harrietepugh** [comment]
This came up in testing. We want it to default to requested amount for approve and partially approve but they can change it. We want it to default to 0 with reject (or just go straight to text field).
