### ISSUE TITLE
Send users automated emails at certain key points of using the product

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/tempo#180]
This issue is about setting up a mailer function to send automated emails to users. 

Required content should be provided in issue #181 

---

### Acceptance Criteria:
- [x] Set up function to automatically send emails 
- [ ] Email notification to confirm that I am now a member/Earn Group/spend partner of Tempo Time Credits when I first sign up
     - [ ] For members if signing up using a link from an Earn Group, remind me that I am now registered to earn Tempo Time Credits with [Earn Group Name]
- [ ] Email notification to confirm that as a member, I am now signed up with [Earn Group Name]
- [ ] A Member receives an email when they have successfully registered for an account
- [ ] A Member receives an email when they have been added to a group
- [ ] Email notification when member has earned Time Credits OR received Time Credits from another member
- [ ] A Member who has gifted Time Credits to a new user receives an email when a user collects their gifted Time Credits
- [ ] An Earn Group receives an email when they receive / partially receive / have their request denied for Time Credits from Tempo
- [ ] Tempo Staff receives an email when an Earn Group requests Time Credits
- [ ] If the Earn Group has added themselves as a volunteer and signs up, and Earn Groups is part of a programme, Tempo receives an email
- [ ] If a member spends Time Credits

**Comment by JonnyBuck16** [comment]
@harrietepugh I just added an email notification for when a member is removed by a customer. do you think is needed/necessary?

**Comment by harrietepugh** [comment]
What would be the purpose of the email? Its kind of negative so I'd say no. A group should only really remove someone if they're inactive so I don't know that we'd need to draw attention to this. I don't think it would provide them with a better experience.

**Comment by JonnyBuck16** [comment]
Cool - i've removed!

**Comment by thejoefriel** [comment]
I have added the extra email to be sent out when members spend time credits
