### ISSUE TITLE
Automated Emails - Required Content

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/tempo#181]
We need content for the automated emails that would be sent out. Details of the issue here: https://github.com/yalla-coop/tempo/issues/180

---

### Acceptance Criteria:
For each of the emails below we need:
- Email address the email would be sent from (e.g. help@wearetempo.org)
- Subject
- Body

Emails needed:
- [x] Set up function to automatically send emails 
- [x] Email notification to confirm that I am now a member/Earn Group/spend partner of Tempo Time Credits when I first sign up
     - [x] For members if signing up using a link from an Earn Group remind me that I am now registered to earn Tempo Time Credits with [Earn Group Name]
- [x] Email notification to confirm that as a member, I am now signed up with [Earn Group Name]
- [x] A Member receives an email when they have successfully registered for an account
- [x] A Member receives an email when they have been added to a group
- [x] Email notification when member has earned Time Credits OR received Time Credits from another member
- [x] A Member who has gifted Time Credits to a new user receives an email when a new user collects their gifted Time Credits
- [x] An Earn Group receives an email when they receive / partially receive / have their request denied for Time Credits from Tempo
- [ ] An Earn Group receives an email when a member they've invited signs up with them.
- [x] Tempo Staff receives an email when an Earn Group requests Time Credits
- [x] Tempo Staff receives an email when an Earn Group signs up to the platform / is registered
- [ ] If the Earn Group has added themselves as a volunteer and signs up, and the Earn Group is part of a programme, Tempo receives an email
- [x] A New member who receives gifted Time Credits from an existing member receives an email when this happens.
- [ ] An Earn Group receives an email when they receive Time Credits back from one of their members

**Comment by harrietepugh** [comment]
I think the "new user" bit of the Gifting email is unnecessary. I think you should be notified of someone collecting the gifted Time Credits whether they are new or existing.

**Comment by harrietepugh** [comment]
[Automated email content - Members.docx](https://github.com/yalla-coop/tempo/files/4492283/Automated.email.content.-.Members.docx)

**Comment by harrietepugh** [comment]
[Automated email content - Tempo Staff.docx](https://github.com/yalla-coop/tempo/files/4492432/Automated.email.content.-.Tempo.Staff.docx)

**Comment by JonnyBuck16** [comment]
[Automated email content - Customers.docx](https://github.com/yalla-coop/tempo/files/4494073/Automated.email.content.-.Customers.docx)

**Comment by harrietepugh** [comment]
[Automated email content - Members.docx](https://github.com/yalla-coop/tempo/files/4609038/Automated.email.content.-.Members.docx)

@thejoefriel here is the updated content with new emails for members after spending TCs. I've edited a couple of others too so please use this doc! Cheers!

**Comment by JonnyBuck16** [comment]
![image](https://user-images.githubusercontent.com/61144884/82428062-dc8e6680-9a81-11ea-9f65-65bc633d7ff1.png)

Hey @thejoefriel just seen this email to a group when their Time Credit request was rejected and cross-referenced it with what we have in the word docs above and it's not the same - can we make sure the content in emails is the same as what is in the word docs ? Ta!
