### ISSUE TITLE
Create Hi Res screens

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/tempo#182]
Hey @jema28 just putting in a few reminders for us of things to make sure we cover in hi res:

- [x] Mobile and desktop versions for every screen (except Tempo platforms)
    - [ ] For Tempo we just need it for the responding to Time Credit Requests and dashboard
- [ ] Group together Common Components once we've got them all 
- [ ] Make sure we cover the pop up messages so we've got every element covered

**Comment by thejoefriel** [comment]
Hi @JudeLuckett here's our report on the colour checking. As I say overall we are art AAA compliance (which is the golden standard :) ) as we knew accessibility is important. 

However, there are a few points of consideration which I've highlighted in this document. Feel free to add your thoughts as comments directly to that document or to reply in here - whichever is easiest for you:

https://www.notion.so/Accessibility-Report-e8171388ac8a470eb1183ff3753933a7

**Comment by JudeLuckett** [comment]
Hi @thejoefriel  thanks for this. Responses:

Fine with the changed main blue.

Cyan - yes to changing the customer dashboard use, maybe to purple? Think we will also need to redo the membership card as that's now cyan; can @jema28 have a go using an alternative colour for the front shape? Sad though :(

Happy leaving the rest of the content as is - the pink in the transaction history/share the love is not as essential, same for the footer. And they look so nice!
