### ISSUE TITLE
Release 1 BONUS Feature Prioritisation

### ISSUE THREAD

**Issue by JonnyBuck16** [yalla-coop/tempo#186]
Harriet and I have discussed how we would like to prioritise the BONUS features in Release 1, and this can be found here:

[Release 1 BONUS Feature Prioritisation .pdf](https://github.com/yalla-coop/tempo/files/4409729/Release.1.BONUS.Feature.Prioritisation.pdf)

@JudeLuckett @thejoefriel - anything you'd like to discuss?

**Comment by JudeLuckett** [comment]
I concur!

**Comment by harrietepugh** [comment]
We'll see how members get on in testing but we may need to put How to Spend Time Credits in the nav menu as Jude suggested, which would mean re-jigging the list above. It would be pretty important for members to know how to spend and may well end up at number 2 (after emails) if not number 1.
