### ISSUE TITLE
List Common Components & Layouts

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/tempo#192]
@jema28 once the wireframes are designed, we need to put the list of common components to be built in here. This is top level where we list the component that needs to be built along with where in Figma it is.

As an example:
- [ ] Button (Style Guide / Buttons)

### Please list them below
- [ ] Component to go here

**Comment by fadeomar** [comment]
## Menu :- 
### 1- MenuLink : 
props (text, link, isActive)
the MenuLink will displays in the list of links in the menu and the shape will depend on isActive prop
if isActive will look like : 
![Screenshot from 2020-04-19 12-54-06](https://user-images.githubusercontent.com/39485495/79684807-e59ad680-823c-11ea-80a8-bb71cf4c3a93.png)

and if not will look like : 
![Screenshot from 2020-04-19 12-55-10](https://user-images.githubusercontent.com/39485495/79684831-06632c00-823d-11ea-9480-1910286a2110.png)

### 2- memberMenu : 
  - for mobile view : 
    * when mnue closed : 
      bar in the top of screen contains Mneu word and burger menu
![Screenshot from 2020-04-19 13-05-35](https://user-images.githubusercontent.com/39485495/79685067-7cb45e00-823e-11ea-9308-7977efbcd697.png)

    * when mnue opened : 
      fullscreen with a list of MenuLinks and close btn in the corner 
![Screenshot from 2020-04-19 13-07-25](https://user-images.githubusercontent.com/39485495/79685101-bc7b4580-823e-11ea-9a21-504c84ee5495.png)

  - for desktop view : 
     side section covers all the page contains   
       1- Tempo Logo
       2- the balance of credit card
       1- a list of MenuLinks
![Screenshot from 2020-04-19 13-12-49](https://user-images.githubusercontent.com/39485495/79685204-7f638300-823f-11ea-870c-4ea35a887eae.png)

**Comment by fadeomar** [comment]
## the Button : 
take many props : 
  * the color ( for background color )
  * the text 
  * the textColor 
  * the size
  * callback  
 The button in all signup page, all login page, onboarding pages, giving out screens, accept time credits screens and staff dashboard
with to sizes : 
  1- the width fit the content and the button (small)
  2- take full width and the content in the center  (large)
and background color of : 
  1- grey
  2- blue
  3- none (with border only)

and text color of : 
  1- white 
  2- black
3- blue
![Screenshot from 2020-04-19 14-47-34](https://user-images.githubusercontent.com/39485495/79686964-c146f600-824c-11ea-95fc-38350c66f5aa.png)

![Screenshot from 2020-04-19 14-48-49](https://user-images.githubusercontent.com/39485495/79686985-e76c9600-824c-11ea-8a2b-53da77118f9e.png)

![Screenshot from 2020-04-19 14-55-10](https://user-images.githubusercontent.com/39485495/79687132-cce6ec80-824d-11ea-8009-be74da5a1c78.png)

![Screenshot from 2020-04-19 14-57-13](https://user-images.githubusercontent.com/39485495/79687187-1b948680-824e-11ea-95ea-23b97603d206.png)

**Comment by fadeomar** [comment]
## Input Component:
 props:   label,  placeholder and handleChange functions

![Screenshot from 2020-04-19 15-28-47](https://user-images.githubusercontent.com/39485495/79687804-7cbe5900-8252-11ea-8644-9cc4dd6b9406.png)

**Comment by thejoefriel** [comment]
Closing this issues as this is all stored in figma and storybook
