### ISSUE TITLE
[component] Buttons

### ISSUE THREAD

**Issue by fadeomar** [yalla-coop/tempo#208]
* full-width button 
![Screenshot from 2020-04-19 14-47-34](https://user-images.githubusercontent.com/39485495/79688340-64e8d400-8256-11ea-8c18-3fe376ec8dc3.png)
  * width fit the contents 
![Screenshot from 2020-04-19 14-48-49](https://user-images.githubusercontent.com/39485495/79688355-7cc05800-8256-11ea-9e04-e94a9c42870e.png)

  * color : ( blue, grey, none )
  * textColor: (blue, white, black)
  * callback function

**Comment by jema28** [comment]
@fadeomar For the majority of mobile buttons we want the width to be a static 315px so there's always a 30px margin on either side :)

**Comment by thejoefriel** [comment]
Hi @jema28 that will still change on different mobile screens though won't it? I.e. a 315px button will have more margin on a iphone 8 vs iphone SE
