### ISSUE TITLE
Set up error messages file

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/tempo#219]
This file should map between error codes and error messages so we are always consistent in the messages displayed to the user.

**Comment by RamyAlshurafa** [comment]
Hey @thejoefriel @dupreesi @fadeomar @ashatat 
here is the error shape should be returned from the backend
```
{
    "error": "Not Found",
    "httpStatusCode": 404,
    "date": "2020-04-28T10:26:02.022Z",
    "message": "Page not found"
}
```
