### ISSUE TITLE
design issues sign up/login

### ISSUE THREAD

**Issue by dupreesi** [yalla-coop/tempo#286]
### Acceptance Criteria:
- [x] inputs need to be centered
- [x] drop down needs to increase field height when mutliple inputs are selected (both mopbile and desktop)
- [ ] sign up and login should be forms, so submitting by `enter` should work

<img width="469" alt="Bildschirmfoto 2020-05-04 um 10 58 43" src="https://user-images.githubusercontent.com/23721486/80951205-b9b05100-8df7-11ea-9193-ab4bfc206be5.png">

- [ ] email exists error should also be shown underneath email field and border of field should be red

**Comment by thejoefriel** [comment]
Hey @ali-7 the first two points on this have been fixed, but the enter issue needs to be done please :)
