### ISSUE TITLE
Having selected to accept time credits without logging in I am prompted to select my venue

### ISSUE THREAD

**Issue by JonnyBuck16** [yalla-coop/tempo#29]
__Is there an associated User Story?__
#27 

__Is this part of a User Journey?
#23
In particular this is the journey of a spend partner who doesn't remember their log in details

_Add the User Journey issue number here (if part of a user journey but doesn't exist, first create an issue for the user journey)_

### Acceptance Criteria:
- [ ] Explanatory text at the top (Tempo to supply)
- [x] Dropdown list of venues
- [x] I can type in to filter the venues (this is fine as long as we use a like antd)
- [x] Select button
- [ ] On confirm take them to the Accept Time Credits page (#26 ) with access to the details they would have if they'd logged in, BUT no access to insights

**Comment by RamyAlshurafa** [comment]
suggestion on functions to use/create 
- front-end: 
  - [ ] use  `api-calls/spend-partners.js` => `getSpendPartners` to fetch all spend partners
  - [ ] on selecting one of the spend partners use `api-calls/auth.js` => `temporaryLogin` with `/auth/temp-login` route and post the speand partner user id (other thing should be handled in the login issue #20 ) 
- back-end:
  - [ ] controller `/modules/spend-partner/controllers/get-spend-partners.js`
  - [ ] use-cases `get-spend-partners(role)`
  - [ ] query `/modules/spend-partner/model/find.js` and create `findSpendPartnersForPublic` query
  - [ ] from the controller call  `get-spend-partners.js` without params
  - [ ] in the use case check for role 
  ```js
  if(!role) { 
    findSpendPartnersForPublic()
  } esle { // to be covered in another user stories }
  ```

  - [ ] the query should filer users on `role= spendPartner` and join users with spendPartnersProfiles to get the name

**Comment by dupreesi** [comment]
frontend: 
- [ ] create Autocomplete input common component
