### ISSUE TITLE
When I give away credits in Activity it says Default Activity even though I selected a Category?

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/tempo#313]
This is in Earn Groups

http://www.clipular.com/posts/5652749495304192?k=8jkuGliEQQSZZqdSTs97v1xF8Jo

It also shouldn't show default activity in the activity name either

**Comment by RamyAlshurafa** [comment]
cant replicate the bug
![image](https://user-images.githubusercontent.com/34629478/81570207-f1476c00-93a8-11ea-83de-de407895b000.png)
