### ISSUE TITLE
Member details in Tempo don't seem to be correct

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/tempo#343]
If you look here it says the balance is 2 despite the transactions indicating this isn't the case, that they haven't spent any credits (despite there being a spend transaction in their history) and that they haven't gifted credits (despite there being gift transactions in their history) 

http://www.clipular.com/posts/5639110960873472?k=aopKNLO6Dg1GttGxwuQO0o85bR8

- Also +/- symbols aren't getting rendered correctly (everything is +)

**Comment by dupreesi** [comment]
@thejoefriel can you check this pls?
https://www.loom.com/share/77c8806fd0b9486b9f590772d4f7f184

**Comment by dupreesi** [comment]
https://www.loom.com/share/53a8447852434fe8bf69455efe9817da
