### ISSUE TITLE
Earn Group Dashboard All Time Stat is smaller than the other stats

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/tempo#346]
@ashatat I feel you fixed this already? However, I've noticed the issue again on the stats in earn group dashboard. 

http://www.clipular.com/posts/5298639474524160?k=nyqbm7dUzcQX6EbbLLWzL6mCK8M

http://www.clipular.com/posts/5777945644498944?k=8nXUd8K6jfQvr1ff7BmhGpwkSVY

**Comment by ashatat** [comment]
@thejoefriel  I think it is fixed now
