### ISSUE TITLE
For each transaction I can see the id of the person who spent the credits, the first half of their postcode, the number of credits, the date, and which activity they spent it on

### ISSUE THREAD

**Issue by JonnyBuck16** [yalla-coop/tempo#35]
__Is there an associated User Story?__
#33 #34 
__Is there an associated User Journey?__
#32 

### Acceptance Criteria:
- [ ] Records ordered by date with newest first
- [ ] Shows fields in line with the wireframes (except Postcode as we don't have that in release 1)

**Comment by harrietepugh** [comment]
We realised it might also be useful to collect the time of Time Credit transactions for both earning and spending (but especially spending). In future this would give us data on when people are more likely to spend (e.g. AM, PM, night). The earning data won't be as useful as its not live but may still have some value.

**Comment by thejoefriel** [comment]
OK thanks @harrietepugh so we will definitely store this in the database and we should discuss at some point how you want this visualised on the staff side
