### ISSUE TITLE
I can view information on my home screen

### ISSUE THREAD

**Issue by harrietepugh** [yalla-coop/tempo#37]
On my home screen, I can see a menu button in the top right hand corner, my membership ID, a 'Welcome back, [my name]" message, how many Time Credits I have (my balance), an Earn Tempo Time Credits section (greyed out) with side scroll menu of activities, a Spend Tempo Time Credits section with side scroll menu of activities, a Gift Tempo Time Credits section with Share the Love button and a My Tempo Time Credits History section displaying my last 5 recent transactions

__Is this part of a User Journey?__
#21 

---

### Acceptance Criteria:

- [ ] Membership ID 
- [ ] "Welcome back, [Member Name]" message
- [ ] Total Credits they have
- [ ] Earn Time Credits section (side scroll) with opportunities to earn Time Credits and Find More link (greyed out) (hard coded and don't click anywhere currently - clicking says "Feature coming soon")
- [ ] Spend Time Credits section (side scroll) with opportunities to spend Time Credits and Find More link (greyed out) (hard coded and don't click anywhere currently - clicking says "Feature coming soon")
- [ ] Give Time Credits section with Share the Love button (don't click anywhere currently - clicking says "Feature coming soon")
- [ ] Time Credits History (last 5 transactions)
- [ ] Click to View Time Credits History

**Comment by harrietepugh** [comment]
@thejoefriel need to discuss the spend section. For the Live Test in Haringey, I think we will need a couple of spend opps hard coded in so they know where to go and how to spend. Is that right?

**Comment by harrietepugh** [comment]
@thejoefriel I'm nervous about the side scrolls as they did cause a bit of a problem in user-testing. My instinct is that they weren't obvious to users because they were testing the platform on a computer, and that if they had been using the app on a phone, they would intuitively used the side scrolls. This isn't something we'll be able to test properly until the Built Test, so I'm just flagging the risk around building the side scrolls and then having to redesign this section if it doesn't prove effective in testing. Is this a big deal? I want to stick with the side scrolls because I think it looks much nicer!!

**Comment by thejoefriel** [comment]
Cool, thanks for that heads up Harriet. I'd suggest @jema28 that when we do some hi res testing we test it the prototype on a phone just to see if the same problem comes up.

**Comment by thejoefriel** [comment]
@harrietepugh with the "My Groups" section - can I just confirm what that is?

**Comment by harrietepugh** [comment]
@thejoefriel lets try My Groups and see if that works in HR test. When Earn Time Credits is ready, I don't think it has to be just volunteer opps for their own groups no.

**Comment by thejoefriel** [comment]
@jema28 looping you in on this so you can adjust the wireframes to a My Groups button please

**Comment by dupreesi** [comment]
@thejoefriel I'm excluding Member transaction history from this issue as otherwise it gets too big and we might be able to make use of a common time credits history component
