### ISSUE TITLE
missing data in members table (admin view)

### ISSUE THREAD

**Issue by RamyAlshurafa** [yalla-coop/tempo#371]
for new members

![image](https://user-images.githubusercontent.com/34629478/81688868-86f30200-9462-11ea-8573-e82e66aca111.png)

**Comment by dupreesi** [comment]
same on earn groups profile
<img width="964" alt="Bildschirmfoto 2020-05-12 um 15 53 44" src="https://user-images.githubusercontent.com/23721486/81700331-d0dee680-9468-11ea-9cd2-a2aa5efc6f1c.png">
