### ISSUE TITLE
I can view my Time Credits History

### ISSUE THREAD

**Issue by harrietepugh** [yalla-coop/tempo#38]
When viewing my last 5 recent transactions I can see the Activity Type, relevant Earn Group or  Spend Partner, Number of Time Credits added or deducted, my updated balance and at the bottom a link to View Time Credits History 
If I click View Time Credits History, I am taken to the My Time Credits History page where I can see all my transactions

__Is there an associated User Story?__
#39 

__Is this part of a User Journey?__
#21 

---

### Acceptance Criteria:
- [ ] Table with data 
- [ ] Activity Type
- [ ] Earn Group/Spend Partner name
- [ ] Number of Time Credits added or deducted
- [ ] Updated Balance
- [ ] If a transaction is member to member, you cannot click that member to get any more details
- [ ] Table grouped in sections by date the transaction took place

Bonus:

- [ ] Partner name clicks to the Partner's profile
- [ ] Click the record to view more information (e.g. the activity description if provided, timestamp)

**Comment by harrietepugh** [comment]
@thejoefriel one of the bonus acceptance criteria in Whimsical is "partner is the name that goes to them" - think it was late; not sure what this is meant to be :)

**Comment by harrietepugh** [comment]
@JudeLuckett @JonnyBuck16 I've simplified the language from 'Transaction History' to 'Time Credits History' as I think the word transaction is unnecessary. What do you think and should we make this consistent across all users?

**Comment by JudeLuckett** [comment]
Maybe we can try that but ask people?

**Comment by harrietepugh** [comment]
@thejoefriel do we need to make a log of things to ask during user testing? e.g. language
