### ISSUE TITLE
Jude's First Issue!!

### ISSUE THREAD

**Issue by JudeLuckett** [yalla-coop/tempo#4]
This is the first issue. Enable Jude to see the data she wants when she logs in

- [ ] Get @thejoefriel to reply with a comment

- Yes
- No

Should look like this 
![Spice journey 1](https://user-images.githubusercontent.com/56549428/74735276-3d6e8e80-5248-11ea-9cc4-852d1a15e535.png)

**Comment by thejoefriel** [comment]
Reply with comment

**Comment by thejoefriel** [comment]
Hey @JudeLuckett this is another comment 👍

**Comment by thejoefriel** [comment]
One more comment for you @JudeLuckett
