### ISSUE TITLE
INCORRECT STATS VS TABLE NUMBERS FETCHED FROM BACK END

### ISSUE THREAD

**Issue by dupreesi** [yalla-coop/tempo#400]
Relates issues 41, 43, 152

1. Earn group, see my volunteers (Chrome 81 on Windows 10)(41)
There is difference between the number of Time Credits listed in the Time Credit transaction table, and then those listed in the activity detail view
https://tempo365.sharepoint.com/Digital/MVP%202020/Forms/AllItems.aspx?originalPath=aHR0cHM6Ly90ZW1wbzM2NS5zaGFyZXBvaW50LmNvbS86ZjovZy9EaWdpdGFsL0VpRldzMzlYTFRCSHVzQU5iRVRnY3pFQjNxaVBhRndET0pjQlRXVGJqUnEzVlE%5FcnRpbWU9X0R5V21hVDQxMGc&id=%2FDigital%2FMVP%202020%2FTesting%2FR1%20Testing%2FBug%20Reporting%2FBug%2041%2Emp4&parent=%2FDigital%2FMVP%202020%2FTesting%2FR1%20Testing%2FBug%20Reporting

2. Spend Partner, see insights (Chrome 81 on Windows 10)(43)
Headline figures are wrong
https://tempo365.sharepoint.com/Digital/MVP%202020/Forms/AllItems.aspx?originalPath=aHR0cHM6Ly90ZW1wbzM2NS5zaGFyZXBvaW50LmNvbS86ZjovZy9EaWdpdGFsL0VpRldzMzlYTFRCSHVzQU5iRVRnY3pFQjNxaVBhRndET0pjQlRXVGJqUnEzVlE%5FcnRpbWU9X0R5V21hVDQxMGc&id=%2FDigital%2FMVP%202020%2FTesting%2FR1%20Testing%2FBug%20Reporting%2FBug%2043%2Emp4&parent=%2FDigital%2FMVP%202020%2FTesting%2FR1%20Testing%2FBug%20Reporting

3. Staff, view all customers with data (Chrome 81 on Windows 10)(152)
Earn group page data querying wrong - saying 101% of TC spent, 4622 TC earned which is not the same as the front page, etc
![thumbnail](https://user-images.githubusercontent.com/23721486/82034481-8a72cd00-969e-11ea-9295-adc051b4357d.png)

**Comment by thejoefriel** [comment]
All looks good 👍
