### ISSUE TITLE
MEMBERS AREN’T LOADING / BEING FETCHED PROPERLY

### ISSUE THREAD

**Issue by dupreesi** [yalla-coop/tempo#403]
related issues: 25, 29, 38, 81, 132, 140, 147

1. Earn group, see my volunteers(Chrome 81 on Windows 10)(25)
I am able to give out Time Credits to more members than I have in My Members
https://tempo365.sharepoint.com/Digital/MVP%202020/Forms/AllItems.aspx?originalPath=aHR0cHM6Ly90ZW1wbzM2NS5zaGFyZXBvaW50LmNvbS86ZjovZy9EaWdpdGFsL0VpRldzMzlYTFRCSHVzQU5iRVRnY3pFQjNxaVBhRndET0pjQlRXVGJqUnEzVlE%5FcnRpbWU9X0R5V21hVDQxMGc&id=%2FDigital%2FMVP%202020%2FTesting%2FR1%20Testing%2FBug%20Reporting%2FBug%2025%2Emp4&parent=%2FDigital%2FMVP%202020%2FTesting%2FR1%20Testing%2FBug%20Reporting

2. Earn group, see my volunteers(Chrome 81 on Windows 10)(29)
Only first name of members appears in the Member table
![thumbnail (1)](https://user-images.githubusercontent.com/23721486/82037385-54374c80-96a2-11ea-90c6-f3fe02a44c18.png)

3. Earn group, see my volunteers(Chrome 81 on Windows 10)(38)
If I click to remove a volunteer, it states loading momentarily then goes back to giving me the remove option
https://tempo365.sharepoint.com/Digital/MVP%202020/Forms/AllItems.aspx?originalPath=aHR0cHM6Ly90ZW1wbzM2NS5zaGFyZXBvaW50LmNvbS86ZjovZy9EaWdpdGFsL0VpRldzMzlYTFRCSHVzQU5iRVRnY3pFQjNxaVBhRndET0pjQlRXVGJqUnEzVlE%5FcnRpbWU9X0R5V21hVDQxMGc&id=%2FDigital%2FMVP%202020%2FTesting%2FR1%20Testing%2FBug%20Reporting%2FBug%2038%2Emp4&parent=%2FDigital%2FMVP%202020%2FTesting%2FR1%20Testing%2FBug%20Reporting

4. Earn group, see my volunteers(Chrome 81 on Windows 10)(81)
I have just added a volunter but they are not showing up?
![thumbnail (1)](https://user-images.githubusercontent.com/23721486/82037461-7204b180-96a2-11ea-950d-a490f3a5ff63.jpeg)

5. Tempo Staff, view all members (Chrome 81 on Windows 11)(132)
no members are coming up listed on the members page while someone else logged in can see them
![thumbnail (2)](https://user-images.githubusercontent.com/23721486/82037498-85b01800-96a2-11ea-9ec6-106333f6c353.jpeg)

6. Earn group, other (Android, Samsung internet) (140)
No members listed on home page or member page
![thumbnail (3)](https://user-images.githubusercontent.com/23721486/82037543-919bda00-96a2-11ea-9de5-1f9b723cd4f2.jpeg)

7. Earn group, see my volunteers (Android, Samsung internet) (147)
I click on a transaction where a member has spent TC with me who has also earned with me but when I click through to their name it says not currently volunteering with me (and no TC earned or spent). It also says there are no transactions with the member. When I click on an earn transaction with the same volunteer I see their correct details and transaction history.
![thumbnail (1)](https://user-images.githubusercontent.com/23721486/82037622-af693f00-96a2-11ea-8033-6adf6a728ebb.jpeg)
![thumbnail (2)](https://user-images.githubusercontent.com/23721486/82037628-b1330280-96a2-11ea-8edb-0286149965f1.jpeg)
![thumbnail (3)](https://user-images.githubusercontent.com/23721486/82037632-b2642f80-96a2-11ea-80db-ac9d22b0eac7.jpeg)
![thumbnail](https://user-images.githubusercontent.com/23721486/82037633-b2642f80-96a2-11ea-8af9-cf129f4006a7.jpeg)
g

**Comment by thejoefriel** [comment]
@ashatat I've noticed that the Members also isn't showing up on the individual earn group page in Tempo Staff pages
