### ISSUE TITLE
STORING TRANSACTIONS AS 0 CREDITS

### ISSUE THREAD

**Issue by dupreesi** [yalla-coop/tempo#404]
related 30, 99, 112

1. Earn group, see volunteer records (Chrome 81 on Windows 10)(30)
Lots of zero's appearing volunteer records
https://tempo365.sharepoint.com/Digital/MVP%202020/Forms/AllItems.aspx?originalPath=aHR0cHM6Ly90ZW1wbzM2NS5zaGFyZXBvaW50LmNvbS86ZjovZy9EaWdpdGFsL0VpRldzMzlYTFRCSHVzQU5iRVRnY3pFQjNxaVBhRndET0pjQlRXVGJqUnEzVlE%5FcnRpbWU9X0R5V21hVDQxMGc&id=%2FDigital%2FMVP%202020%2FTesting%2FR1%20Testing%2FBug%20Reporting%2FBug%2030%2Emp4&parent=%2FDigital%2FMVP%202020%2FTesting%2FR1%20Testing%2FBug%20Reporting

2. Member, view transaction history (Android, Samsung internet)(99) 
Transactions of 0 Time Credits are listed on the transaction history for Jackie, this should not be 
![thumbnail (4)](https://user-images.githubusercontent.com/23721486/82041413-6e742900-96a8-11ea-929f-9a822bbfebdb.jpeg)

3. Member, view transaction history (Apple, Chrome)(112)
On my Time Credits history, some line items says I earned '0' though when I click into the opportunity for more information, it is displayed as 1 Time Credit.

**Comment by thejoefriel** [comment]
Looks fixed 👍 At least I can't recreate this
