### ISSUE TITLE
NOT FETCHING ALL OF THE EARN GROUPS

### ISSUE THREAD

**Issue by dupreesi** [yalla-coop/tempo#405]
related issues: 95

1.) Staff, view all customers (Android, Samsung internet)(95)
The dashboard says there are 2 earn groups with 12 members and 4100 TC earned but only 1 is listed in the table, with 32 members and 822 TC earned. The data is not totalling properly.

**Comment by thejoefriel** [comment]
I've noticed this seems to happen for earn groups who don't have any members: https://www.loom.com/share/289ad4a70b984180a11acb52b5d38104

Once they have a member added to them they then start showing in the table. So that's where the bug is

**Comment by thejoefriel** [comment]
Looking good 👍
