### ISSUE TITLE
Linkedin Mention

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/tempo#41]
Hi @laurajtempo - are you ok if we mention we're working with Tempo on our Yalla LinkedIn?

**Comment by laurajtempo** [comment]
Yep, no problem at all - but if it's OK to keep the nature of the
project/product quiet for now, we'd be grateful. Hopefully at the end of
Tech for Good we'll be able to shout more widely about our learning! Hope
that sounds OK


<http://www.wearetempo.org/>

*Laura Jenner*

Digital Project Manager

T 020 8980 2691 | M 07479948741

W wearetempo.org <http://www.wearetempo.org/> | timecredits.com

A 15 Old Ford Road, Bethnal Green, E2 9PJ

@tempo_tweets <https://twitter.com/tempo_tweets> | facebook.com/timecredits
Sign up to our newsletter <http://eepurl.com/dsN3tr>

Tempo is a Limited Company Registered in England and Wales: Tempo Time
Credits Limited No.06593956, and Registered Charity No. 1135143. The
information contained in this e-mail and any attachments is confidential
and may be legally privileged. If you have received it in error, you are on
notice of its status. It is intended solely for the addressee. Any
unauthorised use is strictly prohibited. If you are not the intended
recipient please notify the sender immediately and delete the e-mail and
any attachments from the system.

**Comment by thejoefriel** [comment]
Thanks Laura! @dupreesi - cc'ing you in so you can see Laura's response.
