### ISSUE TITLE
Total spent % on admin/earn-groups/:id show total % of whole platform but not only for this individual earn group

### ISSUE THREAD

**Issue by dupreesi** [yalla-coop/tempo#414]
please use dev database, log in as staff-super -> check /earn-groups totals and the totals for each earn group. it seems that totals for individual earn groups sum up all totals from platform
e.g. Movers and Shakers has 36%, tasty testers 33% but on each individual earn group page it shows as 66%

**Comment by RamyAlshurafa** [comment]
@dupreesi Fixed

**Comment by thejoefriel** [comment]
I'm leaving this open @RamyAlshurafa as I don't think spend % and showing credits spent is still working properly. I've created issue #468  for this too
