### ISSUE TITLE
I am taken to the Spend Activity page where I see information on the spend activity, my membership ID and quick steps on how to use this to spend Time Credits

### ISSUE THREAD

**Issue by harrietepugh** [yalla-coop/tempo#43]
I see an image, the Activity Name, the Activity Type icon, the Number of Time Credits it will cost, the Spend Partner Venue Name, Availability, Restrictions, Booking Requirements and Details. I am shown my Membership ID and an expandable section with quick steps on How to Spend Time Credits. If I click on Spend Partner Venue Name, I am taken to the Spend Partner Venue Profile.

__Is there an associated User Story?__
#42 
#148

__Is this part of a User Journey?__
#40 

---

### Acceptance Criteria:
- [ ] Header image
- [ ] Activity Name
- [ ] Activity Type Icon
- [ ] the Number of Time Credits it will cost
- [ ] the Spend Partner Venue Name (clickable - relates to #148 )
- [ ] Availability
- [ ] Restrictions
- [ ] Booking Requirements 
- [ ] Details
- [ ] Expandable section on "How to Spend Time Credits"

Bonus: 

- [ ] Reviews
- [ ] Average rating
- [ ] Form to add your own review and give rating

**Comment by JonnyBuck16** [comment]
Not sure this should be bonus @thejoefriel - won't we have some coded into the first release?
