### ISSUE TITLE
give out tc counter doesn't let me type correctly

### ISSUE THREAD

**Issue by dupreesi** [yalla-coop/tempo#431]
https://www.loom.com/share/aa9829fa4cf14fd4a7002614f403d69b

**Comment by RamyAlshurafa** [comment]
@dupreesi i think @thejoefriel added a max constraint to this field

**Comment by dupreesi** [comment]
the backspace doesn't delete the input (stays at min of 1), not sure if this is an issue actually...

**Comment by thejoefriel** [comment]
I think it is an issue @dupreesi as it means they can't then type in the credits except in multiples of 10

**Comment by thejoefriel** [comment]
> @dupreesi i think @thejoefriel added a max constraint to this field

I didn't
