### ISSUE TITLE
My membership ID is accepted/not accepted

### ISSUE THREAD

**Issue by harrietepugh** [yalla-coop/tempo#44]
I give my membership ID to the spend partner
If verified, the Time Credits are deduced from my balance and I can go into the spend partner successfully
If rejected, I am told why

__Is there an associated User Story?__
#43 

__Is this part of a User Journey?__
#40 

---

### Acceptance Criteria:
Bonus: 
- [ ] We can look at the date they last were on the platform and then highlight the transactions that happened since (some sort of animation?)

**Comment by harrietepugh** [comment]
@thejoefriel do we need acceptance criteria for the rejected messages? I want them to be nice. If yes, does this need separating out into two stories for accepted and rejected? 

Also, I'd like an animation when the transaction takes place (like Google Pay). Should I add this here? Is this a bonus? The current bonus criteria is quite advanced (based on last transaction), I'd rather have an acceptance criteria for an animation to appear every time Time Credits are spent

**Comment by thejoefriel** [comment]
We've got this feature/action covered in the spend partner issue #30 so will close this for now. 

@harrietepugh if you can make a note about animations and then let's discuss later on depending on how the development work is going. At the moment the member wouldn't be doing anything on their phone for the transaction (it's done all via the Spend Partner) so there's no need to show them anything.

**Comment by harrietepugh** [comment]
@thejoefriel yes I suppose they're not doing anything... Time Credits are deduced from their account though, which is quite important. Its like when you receive money on Monzo. You get notified even though you're not technically doing anything. Given its entirely non-essential, I'm happy to pick up if there's time!

**Comment by thejoefriel** [comment]
Yeah makes sense @harrietepugh - the only difference is that we're not an app so we can't send app notifications like monzo, so we'd need to think about how and when we do it. We are looking at the email notification and maybe we think about if we want an update update pop up whenever they come back to the platform?
