### ISSUE TITLE
Design Prototype - Meeting Summary

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/tempo#44]
Hi @laurajtempo sorry for the slight delay. Here's a summary of the key points discussed in our meeting:

- For the charity user, show the total number of credits they've given away in the past 30 days
- A charity can give credits and accept credits (e.g. for yoga), so we need to modify their 'scan credits' to give an option to mark it as credits spent or earned
- For the charity user and the Tempo user, allow them to export all the data to CSV
- For the Tempo user, show the total amount of credits earned and the total amount spent in the past 30 days
- For the Tempo user, put in the user's email address and add the id so it's clear that two users are unique even if they have the same name

Also, depending on once you know the spend partner, we may want to pre-load the activities for each partner to make it easier for them when scanning credits

Is there anything I've missed?

@dupreesi @RamyAlshurafa - please read this summary. I'll look to modify the relevant issues too

**Comment by laurajtempo** [comment]
Hi @thejoefriel and everyone, I think this covers everything we talked through on Tuesday for this price of work. Thanks for summarising, and for talking me through the wireframes this week too. I spoke to a Partnerships Manager in our organisation and he believed the pre-loading of activities would be really helpful - I'll also let you know when I've confirmed with the partner, 
Thanks all!
