### ISSUE TITLE
CSV Export Data issues

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/tempo#445]
- [x] Bug 27 - When I download My members I get Member ID as well. These shouldn't be here.
- [x] Bug 28 - When I download My membersthe time of day they joined is added to the date. Only the date should be here.
- [x] Bug 58 - D.O.B is not being pulled through for members that are non-digital
- [x] Bug 70 - Earn Group field is labelled Customer not Earn Group and the data fields are not coming up in separate columns as I would expect in a CSV
- [x] Bug 77 - When I export the data there is blank fields - so it looks like you can 'report' giving 0 TCs out?
- [x] Bug 196 - When I download members, their last names are merged into the first name column of the spreadsheet
- [x] Bug 210 - No date of last transaction in CSV export for earn groups

**Comment by RamyAlshurafa** [comment]
> Bug 27 - When I download My members I get Member ID as well. These shouldn't be here.

@thejoefriel i can see the ID in the fields to be exported, or they need mean the user id?

**Comment by thejoefriel** [comment]
Hey @RamyAlshurafa they're referring to when Earn Groups export data. Same for bug 28. For the Earn Groups when they export data, they don't get the member's ID
