### ISSUE TITLE
How Time Credits Works tab doesn't display the full page, cuts off part of the bottom of the text. The right side of the page is blank.

### ISSUE THREAD

**Issue by JonnyBuck16** [yalla-coop/tempo#476]
Relates to Bug 106

**Comment by thejoefriel** [comment]
Hi @JonnyBuck16 the screengrab wasn't in the folder. Do you mind attaching to this please so we can see the issue?

**Comment by JonnyBuck16** [comment]
Asking one of our team to provide - will upload as soon as I get my hands on it!

**Comment by JonnyBuck16** [comment]
![Bug 106](https://user-images.githubusercontent.com/61144884/82306110-87d1e980-99b6-11ea-98ff-5d178849a70f.png)

**Comment by thejoefriel** [comment]
OK cool thanks @JonnyBuck16 ! Yeah that was covered in another bug and has now been fixed 👍
