### ISSUE TITLE
On the 'give Time Credits to my group' page, the dropdown loads my keyboard and when I scroll down the dropdown menu doesn't move with the screen, it floats off

### ISSUE THREAD

**Issue by JonnyBuck16** [yalla-coop/tempo#483]
Related to bug 116

**Comment by thejoefriel** [comment]
Screengrabs of bug here:

![Bug 116 (1)](https://user-images.githubusercontent.com/19708921/82292923-9cf14d00-99a3-11ea-8a6f-4592d3deffa3.jpg)

![Bug 116 (2)](https://user-images.githubusercontent.com/19708921/82292935-a084d400-99a3-11ea-8a8c-6578fec73239.jpg)
