### ISSUE TITLE
Home page and Time Credits history transaction table displaying weirdly - 'GIVEN OUT' text going into 2 lines instead of 1 as in wireframes

### ISSUE THREAD

**Issue by JonnyBuck16** [yalla-coop/tempo#484]
Related to Bug 142

**Comment by thejoefriel** [comment]
Screengrab of bug here:

![Bug 142](https://user-images.githubusercontent.com/19708921/82292670-34a26b80-99a3-11ea-82aa-6a138ef5ade4.jpg)
