### ISSUE TITLE
I sign up and am registered to earn Time Credits with an Earn Group

### ISSUE THREAD

**Issue by harrietepugh** [yalla-coop/tempo#49]
I enter my name, email and a password and click sign up
I see a success message that I have been registered with Tempo and added to the volunteering group and I am prompted to see what I can do next with my new account
(Clicking next triggers the onboarding journey)

__Is there an associated User Story?__
#48 

__Is this part of a User Journey?__
#46 

---

### Acceptance Criteria:
- [ ] If successful, add user to database
Validation, error messages:
- [ ] User already exists
- [ ] Invalid password (minimum lower case, uppercase, 8 characters)
- [ ] Invalid email address
- [ ] Required fields not filled in
- [ ] Have agreed to T&Cs

**Comment by harrietepugh** [comment]
@thejoefriel we've discussed it at various points but its not made it into acceptance criteria yet - can we do an email notification to members when they have signed up, been added to a group and earn Time Credits? Can I go ahead and add them in here? Where should I put the content?

**Comment by thejoefriel** [comment]
Hey @harrietepugh I've created an issue for this #180 and a content issue for the emails here #181 👍
