### ISSUE TITLE
Create Jonny's first issue

### ISSUE THREAD

**Issue by JonnyBuck16** [yalla-coop/tempo#5]
Doing something great

- [ ] Get @thejoefriel to reply with a comment 
![Edited Generic NOTE](https://user-images.githubusercontent.com/61144884/74735258-36478080-5248-11ea-8e4b-d44f3e63982f.png)

**Comment by thejoefriel** [comment]
Jonny will only get a notification for this comment

**Comment by thejoefriel** [comment]
@JudeLuckett will get a notification for this comment

**Comment by JudeLuckett** [comment]
@JonnyBuck16 do you get this

**Comment by JudeLuckett** [comment]
@thejoefriel do you get this


[cid:image007.png@01D5E657.9D603990]
Jude Luckett
Product Development Lead
[Telephone] 07446 410377
[World] wearetempo.org<http://www.wearetempo.org/> | timecredits.com<https://timecredits.com/>
[Marker] Studio 301 Pelican House, 144 Cambridge Heath Rd, London E1 5QJ
@tempo_tweets<https://twitter.com/tempo_tweets> | @judeluckett | facebook.com/timecredits<http://facebook.com/timecredits>
Sign up to our newsletter<https://bit.ly/2y6a4yU>

  [cid:image011.png@01D5E657.9D603990]           [cid:image012.png@01D5E657.9D603990]

Tempo is a Limited Company Registered in England and Wales: Tempo Time Credits Limited No.06593956, and Registered Charity No. 1135143. The information contained in this e-mail and any attachments is confidential and may be legally privileged. If you have received it in error, you are on notice of its status. It is intended solely for the addressee. Any unauthorised use is strictly prohibited. If you are not the intended recipient please notify the sender immediately and delete the e-mail and any attachments from the system
