### ISSUE TITLE
Design Issues

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/tempo#502]
- [x] Bug 2 - Can barely read text in the text boxes e.g. "type email here" (could be because my screen is too bright)
- [x] Bug 31 - Sign-up is spelt Signup 
- [x] Bug 36 - Register Member and I want to go back buttons other way round from wireframes
- [ ] Bug 93 - Strange black bar appears at bottom of screen while scrolling
- [x] Bug 111 - in member menu, 'HOW TIME CREDITS WORKS' needs the S removing from WORKS
- [x] Bug 138 - text on the 'Invite a Member' page " your members will be able to; Receive Tempo Time Credits from you" - R doesn't need to be capitalised
- [x] Look to increase the height of the How Time Credits Works bottom banner on spend activities / partners, so we can introduce a bit more top padding to solve this bug 92 - text in blue box at bottom of screen has very narrow top margin

**Comment by fadeomar** [comment]
the placeholder in the app identical to the placeholder in the wireframes, but for this, we can use `gray4` for the placeholder instead of `gray3`will look darker than before

**Comment by thejoefriel** [comment]
gray 3 should be darker than gray 4 right?

**Comment by thejoefriel** [comment]
The placeholder @fadeomar in the wireframes is gray3

**Comment by fadeomar** [comment]
oh yes gray3 should be darker
