### ISSUE TITLE
After accepting TC as spend partner going to insights requires hard refresh to show latest transaction

### ISSUE THREAD

**Issue by dupreesi** [yalla-coop/tempo#509]
https://www.loom.com/share/b2c3e57b64d840d2a7c8da5e858919f8

**Comment by RamyAlshurafa** [comment]
Can you check this again @dupreesi 
i think this been fixed earlier in one of the prs

**Comment by dupreesi** [comment]
@RamyAlshurafa still doesn't work for me. the new record shows in total numbers (x of x records) but doesn't get rendered.
