### ISSUE TITLE
I see a sign up form and a link to click if I already have an account

### ISSUE THREAD

**Issue by JonnyBuck16** [yalla-coop/tempo#56]
Is this part of User Journey?
#59 

### Acceptance Criteria:
- [ ] Welcome to Tempo Time Credits message "Thank people by giving them Tempo Time Credits. They can spend their Tempo Time Credits on new and fun things to do"
- [ ] Name of your organisation
- [ ] Type of Organisation
- [ ] What do you focus on?
- [ ] Select Region
- [ ] Local authority
- [ ] First name
- [ ] Second Name
- [ ] Email 
- [ ] Phone Number
- [ ] Password (min. 1 lower case, 1 uppercase, 8 characters)
- [ ] T&Cs & Consent
- [ ] Sign Up Button
- [ ] "I already have a Tempo account" link
- [ ] If successful, add user to database
- [ ] Validation, error messages:
   - [ ] User already exists
   - [ ] Invalid password (minimum lower case, uppercase, 8 characters)
   - [ ] Invalid email address
   - [ ] Required fields not filled in
   - [ ] Haven't agreed to T&Cs

Local Authority List:

Aberdeen City
Aberdeenshire
Adur
Allerdale
Amber Valley
Angus
Antrim and Newtownabbey
Ards and North Down
Argyll and Bute
Armagh City, Banbridge and Craigavon
Arun
Ashfield
Ashford
Aylesbury Vale
Babergh
Barking and Dagenham
Barnet
Barnsley
Barrow-in-Furness
Basildon
Basingstoke and Deane
Bassetlaw
Bath and North East Somerset
Bedford
Belfast
Bexley
Birmingham
Blaby
Blackburn with Darwen
Blackpool
Blaenau Gwent
Bolsover
Bolton
Boston
Bournemouth, Christchurch and Poole
Bracknell Forest
Bradford
Braintree
Breckland
Brent
Brentwood
Bridgend
Brighton and Hove
Bristol, City of
Broadland
Bromley
Bromsgrove
Broxbourne
Broxtowe
Burnley
Bury
Caerphilly
Calderdale
Cambridge
Camden
Cannock Chase
Canterbury
Cardiff
Carlisle
Carmarthenshire
Castle Point
Causeway Coast and Glens
Central Bedfordshire
Ceredigion
Charnwood
Chelmsford
Cheltenham
Cherwell
Cheshire East
Cheshire West and Chester
Chesterfield
Chichester
Chiltern
Chorley
City of Edinburgh
City of London
Clackmannanshire
Colchester
Conwy
Copeland
Corby
Cornwall
Cotswold
County Durham
Coventry
Craven
Crawley
Croydon
Dacorum
Darlington
Dartford
Daventry
Denbighshire
Derby
Derbyshire Dales
Derry City and Strabane
Doncaster
Dorset
Dover
Dudley
Dumfries and Galloway
Dundee City
Ealing
East Ayrshire
East Cambridgeshire
East Devon
East Dunbartonshire
East Hampshire
East Hertfordshire
East Lindsey
East Lothian
East Northamptonshire
East Renfrewshire
East Riding of Yorkshire
East Staffordshire
East Suffolk
Eastbourne
Eastleigh
Eden
Elmbridge
Enfield
Epping Forest
Epsom and Ewell
Erewash
Exeter
Falkirk
Fareham
Fenland
Fermanagh and Omagh
Fife
Flintshire
Folkestone and Hythe
Forest of Dean
Fylde
Gateshead
Gedling
Glasgow City
Gloucester
Gosport
Gravesham
Great Yarmouth
Greenwich
Guildford
Gwynedd
Hackney
Halton
Hambleton
Hammersmith and Fulham
Harborough
Haringey
Harlow
Harrogate
Harrow
Hart
Hartlepool
Hastings
Havant
Havering
Herefordshire, County of
Hertsmere
High Peak
Highland
Hillingdon
Hinckley and Bosworth
Horsham
Hounslow
Huntingdonshire
Hyndburn
Inverclyde
Ipswich
Isle of Anglesey
Isle of Wight
Isles of Scilly
Islington
Kensington and Chelsea
Kettering
King's Lynn and West Norfolk
Kingston upon Hull, City of
Kingston upon Thames
Kirklees
Knowsley
Lambeth
Lancaster
Leeds
Leicester
Lewes
Lewisham
Lichfield
Lincoln
Lisburn and Castlereagh
Liverpool
Luton
Maidstone
Maldon
Malvern Hills
Manchester
Mansfield
Medway
Melton
Mendip
Merthyr Tydfil
Merton
Mid and East Antrim
Mid Devon
Mid Suffolk
Mid Sussex
Mid Ulster
Middlesbrough
Midlothian
Milton Keynes
Mole Valley
Monmouthshire
Moray
Na h-Eileanan Siar
Neath Port Talbot
New Forest
Newark and Sherwood
Newcastle upon Tyne
Newcastle-under-Lyme
Newham
Newport
Newry, Mourne and Down
North Ayrshire
North Devon
North East Derbyshire
North East Lincolnshire
North Hertfordshire
North Kesteven
North Lanarkshire
North Lincolnshire
North Norfolk
North Somerset
North Tyneside
North Warwickshire
North West Leicestershire
Northampton
Northumberland
Norwich
Nottingham
Nuneaton and Bedworth
Oadby and Wigston
Oldham
Orkney Islands
Oxford
Pembrokeshire
Pendle
Perth and Kinross
Peterborough
Plymouth
Portsmouth
Powys
Preston
Reading
Redbridge
Redcar and Cleveland
Redditch
Reigate and Banstead
Renfrewshire
Rhondda Cynon Taf
Ribble Valley
Richmond upon Thames
Richmondshire
Rochdale
Rochford
Rossendale
Rother
Rotherham
Rugby
Runnymede
Rushcliffe
Rushmoor
Rutland
Ryedale
Salford
Sandwell
Scarborough
Scottish Borders
Sedgemoor
Sefton
Selby
Sevenoaks
Sheffield
Shetland Islands
Shropshire
Slough
Solihull
Somerset West and Taunton
South Ayrshire
South Bucks
South Cambridgeshire
South Derbyshire
South Gloucestershire
South Hams
South Holland
South Kesteven
South Lakeland
South Lanarkshire
South Norfolk
South Northamptonshire
South Oxfordshire
South Ribble
South Somerset
South Staffordshire
South Tyneside
Southampton
Southend-on-Sea
Southwark
Spelthorne
St Albans
St. Helens
Stafford
Staffordshire Moorlands
Stevenage
Stirling
Stockport
Stockton-on-Tees
Stoke-on-Trent
Stratford-on-Avon
Stroud
Sunderland
Surrey Heath
Sutton
Swale
Swansea
Swindon
Tameside
Tamworth
Tandridge
Teignbridge
Telford and Wrekin
Tendring
Test Valley
Tewkesbury
Thanet
Three Rivers
Thurrock
Tonbridge and Malling
Torbay
Torfaen
Torridge
Tower Hamlets
Trafford
Tunbridge Wells
Uttlesford
Vale of Glamorgan
Vale of White Horse
Wakefield
Walsall
Waltham Forest
Wandsworth
Warrington
Warwick
Watford
Waverley
Wealden
Wellingborough
Welwyn Hatfield
West Berkshire
West Devon
West Dunbartonshire
West Lancashire
West Lindsey
West Lothian
West Oxfordshire
West Suffolk
Westminster
Wigan
Wiltshire
Winchester
Windsor and Maidenhead
Wirral
Woking
Wokingham
Wolverhampton
Worcester
Worthing
Wrexham
Wychavon
Wycombe
Wyre
Wyre Forest
York

**Comment by JonnyBuck16** [comment]
Hey @JudeLuckett Can I just check that the above list of local authorities is as at the level required?

**Comment by JudeLuckett** [comment]
Yep, looks perfect!
