### ISSUE TITLE
Hi Res Testing

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/tempo#562]
## Purpose of this issue:
- [ ] Store the Hi res user testing sessions
- [ ] Store who is assigned to work on them and whether remote or in person
- [ ] Link to the Figma prototype
- [ ] Link to User Testing script(s)
- [ ] Link to User Testing Feedback Form (to be filled in by one of our team after they are sent the feedback from Tempo)
- [ ] Discuss which elements we feel are important and require wireframe changes via the notion link (refer to Documentation section in this issue) 

## Documentation
All scripts stored here: https://www.notion.so/User-Testing-8f045c9ac9b749c5b9266f8711113252

All feedback and agreed wireframe changes stored here: TBC @jema28 do you mind adding this please?

## Prototypes
**Member**
DESKTOP: https://www.figma.com/proto/zK1CnfVlTEqBFurpXQTwNa/Tempo-Release-2?node-id=5446%3A891&scaling=scale-down

MOBILE: https://www.figma.com/proto/zK1CnfVlTEqBFurpXQTwNa/Tempo-Release-2?node-id=5587%3A3803&scaling=scale-down

**Customer**
DESKTOP: https://www.figma.com/proto/zK1CnfVlTEqBFurpXQTwNa/Tempo-Release-2?node-id=1708%3A39924&scaling=scale-down

MOBILE: https://www.figma.com/proto/zK1CnfVlTEqBFurpXQTwNa/Tempo-Release-2?node-id=5619%3A9771&scaling=scale-down

**Spend Partner**
DESKTOP: https://www.figma.com/proto/zK1CnfVlTEqBFurpXQTwNa/Tempo-Release-2?node-id=1273%3A37813&scaling=scale-down

MOBILE: https://www.figma.com/proto/zK1CnfVlTEqBFurpXQTwNa/Tempo-Release-2?node-id=5622%3A132426&scaling=scale-down

**Staff**
https://www.figma.com/proto/zK1CnfVlTEqBFurpXQTwNa/Tempo-Release-2?node-id=1273%3A30248&scaling=scale-down

## Agreed User Testing Sessions (please update here)

_### Monday 22nd June

**Member**
- Location: Remote
- Users: Carole
- Contact: mitchell_carole@hotmail.com
- Times: 10am
- Assigned: @jema28 @thejoefriel 
- NEED TO SET UP A ZOOM LINK PLEASE

**Tempo Staff**
- Location: Remote
- Users: Maria Agiomyrgiannaki
- Times: 10:30 - 11:00am 
- Assigned: @JonnyBuck16 
- Meeting link: n/a

**Member**
- Location: Remote
- Users: Irene
- Contact: n0rthernstar58@gmail.com
- Times: 11.30am
- Assigned: @jema28 @thejoefriel 
- NEED TO SET UP A ZOOM LINK PLEASE

**Tempo Staff**
- Location: Remote
- Users: Beth Ward
- Times: 16:15 - 17:00pm 
- Assigned: @JonnyBuck16 
- Meeting link: n/a

_### Tuesday 23rd June

**Earn Group**
- Location: Remote
- Users: Matthew Dring (Wolves Lane)
- Times: 10:00am - 10:45am 
- Assigned: @JonnyBuck16 
- Meeting link: n/a

**Tempo Staff**
- Location: Remote
- Users: Ffion Williams
- Times: 11:00am - 11:45am
- Assigned: @JonnyBuck16 
- Meeting Link: n/a

**Member**
- Location: Remote
- Users: Karolina
- Times: 11.30am
- Assigned: @harrietepugh 

**Tempo Staff**
- Location: Remote
- Users: Hannah Westwell
- Times: 13:00pm - 13:45pm 
- Assigned: @JonnyBuck16 
- Meeting link: n/a

**Member**
- Location: Remote
- Users: David
- Times: 1pm
- Assigned: @harrietepugh 

**Tempo Staff**
- Location: Remote
- Users: Ben Cook
- Times: 13:45pm - 14:30pm 
- Assigned: @JonnyBuck16 
- Meeting link: n/a

**Member**
- Location: Remote
- Users: Shirley
- Times: 2pm
- Assigned: @harrietepugh 

**Spend Partner**
- Location: Remote
- Users: Jonathan and Julia (Barbican)
- Times: 15:00pm - 15:45pm 
- Assigned: @JonnyBuck16 
- Meeting link: n/a

**Tempo Staff**
- Location: Remote
- Users: Sarah
- Times: 3.30pm
- Assigned: @harrietepugh 

_### Wednesday 24th June

**Tempo Staff**
- Location: Remote
- Users: Maria
- Times: 9.30am
- Assigned: @harrietepugh  

**Member**
- Location: Remote
- Users: Katie
- Times: 2pm
- Assigned: @harrietepugh 

**Earn Group**
- Location: Remote
- Users: Nadya Kassam (Wolves Lane)
- Times: 10:00am - 10:45am 
- Assigned: @JonnyBuck16 
- Meeting link: n/a

**Tempo Staff**
- Location: Remote
- Users: Maria
- Times: 12pm
- Assigned: @harrietepugh  

**Tempo Staff**
- Location: Remote
- Users: Fi
- Times: 2pm
- Assigned: @harrietepugh  

**Tempo Staff**
- Location: Remote
- Users: Ami
- Times: 3pm
- Assigned: @harrietepugh  

**Tempo Staff**
- Location: Remote
- Users: Becky Jones
- Times: 15:00pm - 15:45pm 
- Assigned: @JonnyBuck16 
- Meeting link: n/a

**Comment by jema28** [comment]
@JonnyBuck16 @harrietepugh Let's continue adding the feedback for high res in here https://www.notion.so/Release-2-42b91a0643e94ab78b25ebdbe71c5683.

**Comment by JonnyBuck16** [comment]
Thanks @jema28
