### ISSUE TITLE
Third-party Set Up

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/tempo#568]
Set up the third party platforms we need for deployment

---

### Acceptance Criteria:
- [x] Zendesk
     - [x] Create an account for Tempo
     - [x] Integrate with codebase
- [x] Google Analytics
     - [x] Create an account for Tempo
     - [x] Integrate with codebase
- [x] Log Rocket
     - [x] Create an account for Tempo
     - [x] Integrate with codebase

---

### What we need from client 

@JonnyBuck16 @harrietepugh can you please send across

- [ ] Email address to use for Zendesk sign up 
- [ ] Email address to use for Google Analytics
- [ ] Email address to use for Log Rocket

**Comment by JonnyBuck16** [comment]
Hi @thejoefriel please use logins@wearetempo.org for all new accounts
