### ISSUE TITLE
Add Cookie Banner

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/tempo#569]
Set up cookie banner for the platform that includes link to cookie policy

---

### Acceptance Criteria:
- [ ] Add cookie banner
- [ ] Link to cookie policy PDF

_Note: use same banner as set up for Tempo website for consistency_

---

### What we need from the client:

@JonnyBuck16 @harrietepugh do you mind sending across please:
- [ ] PDF for the cookie policy

**Comment by JonnyBuck16** [comment]
Hi Joe - haven't sent this yet because we are going use the same one as for the website, but we will need to change the web-domain that is referenced within it to match the Digital Time Credit domain. Will send across as soon as that is confirmed!
