### ISSUE TITLE
Update Member Sign Up 

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/tempo#590]
__Is there an associated User Story?__

_When signing up as a member I am prompted to answer some further questions about my demographics_

EXPLAINER TEXT: 

At Tempo, we want to reach people from different backgrounds and value everyone's contribution. This means we need to collect information about who is signing up to use Time Credits.

This information will be used anonymously to understand if Time Credits are relevant and accessible for different groups. We will never sell your personal information to third parties.

We would appreciate your help, but you can skip this step below. Thank you.

---

### Acceptance Criteria:
- [ ] Update original page to follow latest wireframe
- [ ] Once they hit sign up they are added to the platform just how it currently works
- [ ] They then see a second page which they can skip 
- [ ] If they answer any of the questions and hit continue, these answers are stored in their profile 
- [ ] Validation to ensure they answer all the questions if they click continue (@harrietepugh is that right or could they just answer one and then hit continue?) 

--- 

### Need form the client 

@JonnyBuck16  @harrietepugh  can you please provide:

- [ ] Total list of options for gender 
- [ ] Total list of options for ethnic group
- [ ] Total list of options for mental health conditions
- [ ] Total list of options for volunteered before
- [ ] We are adding 'I'd prefer not to say' to each one aren't we except Date of Birth?

**Comment by harrietepugh** [comment]
LIST OF ETHNIC GROUPS:

**White**
English / Welsh / Scottish / Northern Irish / British
Irish
Gypsy or Irish Traveller
Any other White background
**Mixed / Multiple ethnic groups**
White and Black Caribbean
White and Black African
White and Asian
Any other Mixed / Multiple ethnic background
**Asian / Asian British**
Indian
Pakistani
Bangladeshi
Chinese
Any other Asian background
**Black / African / Caribbean / Black British**
African
Caribbean
Any other Black / African / Caribbean background
**Other ethnic group**
Arab
Any other ethnic group
Prefer not to say

**Comment by harrietepugh** [comment]
LIST OF GENDER:

Female
Male 
Non-Binary
Trans*
Prefer to self-describe: ___________
Prefer not to say

**Comment by harrietepugh** [comment]
Question should read: Do you have any disabilities, illnesses or mental health conditions? Tick all that apply.
No
Learning disability
Long term health condition
Mental health condition
Physical health condition
Sensory impairment
Other

**Comment by harrietepugh** [comment]
Order of questions: Gender, Ethnicity, Disability, DOB, Ever Volunteered

**Comment by harrietepugh** [comment]
Have you   previously been involved in volunteering?
--
I have never volunteered   before
I have occasionally   volunteered before
I have   volunteered in the past but not recently
I already volunteer regularly

**Comment by harrietepugh** [comment]
@thejoefriel we need a prefer not to say for DOB too please :) maybe just a little tickbox underneath
