### ISSUE TITLE
Update Options / Tags

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/tempo#599]
Update the list of options for:

- [ ] Focus / Cause
- [ ] Spend Activity Type
- [ ] Earn Activity Type

@JonnyBuck16 @harrietepugh can you send across the list(s) and add them here please?

**Comment by harrietepugh** [comment]
@thejoefriel 

CAUSES:
Arts, Culture & Science
Animals
Armed Forces & Emergency Services
Community Development
Disability
Environment, Conservation & Heritage
Poverty Relief
Food & Food Waste
Health & Social Care
Housing & Homelessness
Rights, Religion & Equality
Older People
Schools & Education
Skills & Employability
Sports & Physical Activity
Families & Children
Addiction
Young People

SPEND ACTIVITY TYPES:
Cultural Experiences
Days Out
Education & Training
Fitness & Leisure
Great for Kids
Health & Beauty
Shows & Performances
Live Sport
Play & Entertainment
Room & Equipment Hire
Transport & Accommodation

EARN ACTIVITY TYPE:
Improving Services
Office & Admin Support
Events & Operations
Practical Help
Professional Skills
Promotion & Fundraising
Running an activity or group
Supporting Others
Teaching & Training

**Comment by harrietepugh** [comment]
[Revised Tags.docx](https://github.com/yalla-coop/tempo/files/4830014/Revised.Tags.docx)

**Comment by harrietepugh** [comment]
@thejoefriel can these be in alphabetical order in member searches please :)
