### ISSUE TITLE
(BONUS) I receive an email welcoming me to the platform

### ISSUE THREAD

**Issue by JonnyBuck16** [yalla-coop/tempo#60]
Automated Emails when:
- [ ] A Member receives an email when they have successfully registered for an account
- [ ] A Member receives an email when they have been added to a group
- [ ] A Member receives an email when they have earned Time Credits OR received Time Credits from another member
- [ ] A Member who has gifted Time Credits to a new user receives an email when a new user collects their gifted Time Credits
- [ ] A Customer receives an email when they have successfully registered for an account
- [ ] A Customer receives an email when they receive Time Credits from Tempo
- [ ] Tempo Staff receives an email when a Customer requests Time Credits

**Comment by thejoefriel** [comment]
Adding these to #180 and closing this issue
