### ISSUE TITLE
Add Programme Feature

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/tempo#600]
__Is this part of a User Journey?__

_As a staff member I can create, edit and manage programmes for Tempo_

---

### Acceptance Criteria:
- [ ] Create / edit a programme
- [ ] View all programmes
- [ ] View individual programme
- [ ] Add / remove groups to a programme
- [ ] Export data 
- [ ] Respond to TC requests within a programme 

### **IMPORTANT - HOW TCs ARE ASSOCIATED TO A PROGRAMME**
There are two ways that a TC becomes associated with a programme:
1. They are issued by the programme 
2. They are accepted by an earn group while they are part of the programme 

A TC's 'journey' always ends at the point that the TC is spent by the Member on a spend activity (whether this is with an earn group or spend partner/venue). If the TC is gifted from member to member, they are still linked to the programme and count towards the Gifted stat - their journey **only** ends once it is spent

IF the TC is spent with an Earn Group who is part of a programme, the TC then starts a new 'journey' basically and becomes associated with the programme that earn group is part of. 

IF the TC is spent with an Earn Group who is **not** part of a programme, the TC then starts a new 'journey' basically and is not associated to any programme (even if the Earn Group is then later added to a programme) 

An overview of the flow is here:
![image](https://user-images.githubusercontent.com/19708921/85850969-bdcc6f80-b7a5-11ea-9dbe-8e253908ae9a.png)

**Comment by harrietepugh** [comment]
@thejoefriel the gift % is only against individual member stats to show the % of Time Credits a member has gifted (ie to show member behaviour). For programmes the gifted stat is just the number of gift transaction

**Comment by harrietepugh** [comment]
Otherwise, yes @thejoefriel this is correct!

**Comment by thejoefriel** [comment]
Ah ok so the gifted in programmes shouldn't be a % then? it should be a total number right?

**Comment by thejoefriel** [comment]
Cool and to check is the number (e.g. 23) the number of gift transactions OR the number of TCs gifted @harrietepugh ?

**Comment by harrietepugh** [comment]
I think the number of gift transactions is most relevant?

**Comment by thejoefriel** [comment]
OK cool. Do you think then we should have the title 'Gifts' instead of 'Gifted'? Gifted seems to imply that we're referring to the amount of TCs that have been gifted

**Comment by harrietepugh** [comment]
Yes - this will need an explainer / question mark

**Comment by thejoefriel** [comment]
ok I'll put that in now
