### ISSUE TITLE
Confirm where we should have the ? icon and what each one should say

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/tempo#603]
Hey @harrietepugh @JonnyBuck16 we've got lots of question mark icons 

For each one please include:
- [ ] Page 
- [ ] The piece of text where the ? mark should be 
- [ ] What the helper text should say when clicked

**Comment by JonnyBuck16** [comment]
[TEMPO STAFF EXPLAINERS.docx](https://github.com/yalla-coop/tempo/files/4837622/TEMPO.STAFF.EXPLAINERS.docx)

**Comment by thejoefriel** [comment]
Hey @fadeomar here are the question text info
