### ISSUE TITLE
Get invidiual programme details (BACK END)

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/tempo#607]
__Is this part of a User Journey?__

https://github.com/yalla-coop/tempo/issues/600

---

### Acceptance Criteria:

- [x] **Balance** - the programme budget minus number of TCs issued by the programme (@harrietepugh - can this go into minus number or would you want us to stop the staff member being able to give out further TCs?) 

- [x] **Top stats**
- [x] Earn groups - total earn groups currently part of programme
- [x] Members Reached - this is all members who have been reached by the programme, this includes:
    - Currently actively volunteer for an earn group part of the programme
    - Have received credits associated from the programme (gifted, given)
- [x] Spend Venues - total spend venues (including earn groups who have accepted TCs from the programme for spend activities) who have accepted TCs associated with the programme
- [x] Transactions - total transactions that have involved TCs from the programme (given out, gifted, spent, issued) 

_NOTE: For the Members, Spend Venues and Transactions, these will be exports rather than pages, which can be covered in this issue #591_

- [x] **Programme Details**

- [x] **Programme Data**
- [x] Issued - total credits issued by the programme 
- [x] Earned - total credits associated with the programme that have been given out by the earn groups 
- [ ]  % Spent - % Programme Time Credits given out by Earn Groups that are associated with the Programme - refer to #600 for more details on associating TCs to programmes
- [ ] Community Spend - TCs associated with the programme that have been spent with Earn Groups (i.e. spend activities that earn groups have created) - @harrietepugh can you confirm this is right please?
- [ ] Gifts - Any time a member has gifted TCs to another member that involves some of TCs from the programme. NOTE: this is number of gift transactions NOT number of TCs gifted

- [x] **Time Credits requests** - this would be requests by any earn groups currently part of that programme 
- [x] **Previous requests** - archive of handled requests from above

- [x] Connect with front end #602

**Comment by harrietepugh** [comment]
@thejoefriel balance cannot go into minus no

**Comment by harrietepugh** [comment]
Needs updating with % Spent with Spend Venues and % Spent with Earn Groups  @thejoefriel

**Comment by harrietepugh** [comment]
Also Gifts now needs updating following our conversation this afternoon! Sorry!

**Comment by harrietepugh** [comment]
@thejoefriel previous requests to be in order of when the TCs were issued (date processed) not data requested
