### ISSUE TITLE
Find Earn Groups Pages (FRONT END)

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/tempo#612]
__Is this part of a User Journey?__

#611 

---

### Acceptance Criteria:

**General:**
- [ ] Set up how you intend data to come from server so it can then be connected
- [ ] Filter groups by location - fill options with total list of options found from the public earn groups sent from server
- [ ] Filter groups by cause
- [ ] Filter groups by activity type
- [ ] Ensure you can filter by location and cause / activity type
- [ ] Pagination - let's show initially 12 activities per page
- [ ] List Earn Groups ordered by number of active members

**Member:**
- [ ] Update dashboard

**Earn groups:**
- [ ] Create initial front page that shows earn groups and spend activities https://www.figma.com/file/zK1CnfVlTEqBFurpXQTwNa/Tempo-Release-2?node-id=5507%3A6948

**Comment by harrietepugh** [comment]
@thejoefriel when you say 'list groups in order of active members' - you mean before a search has taken place right? So that would be the default, then location, then cause / activity type relevance?

**Comment by thejoefriel** [comment]
Yeah before a search has taken place. However, if I understand it correctly, if someone filters by London and Admin & Office Support (for example) we would only show them the activities that match that right? In which case relevance will never come into it for ordering at this stage (ordering by relevance will become more a thing when you can search by multiple types and via postcodes etc). So we would always most likely order by popularity but then apply filters if they've selected a filter?
