### ISSUE TITLE
Get all Earn Group Listings

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/tempo#613]
__Is this part of a User Journey?__

https://github.com/yalla-coop/tempo/issues/611

---

### Acceptance Criteria:
- [x] Update DB to ensure earn group profiles are now in line with latest architecture #577 
- [x] Query to fetch all earn group listings (public listing only) 
     - [x] In the query we also need the total members and to order the earn groups based on this size (this is indication of popularity
- [ ] Connect with Front end pages to find earn groups https://github.com/yalla-coop/tempo/issues/611
- [ ] Update member dashboard query to ensure it's fetching the three most popular earn groups and connect with front end 

### What we need from Tempo

@harrietepugh @JonnyBuck16 - please confirm you're happy with our definitely of popularity and that we should order it like this

**Comment by harrietepugh** [comment]
Yes happy @thejoefriel as long as its overriden by location or  AT / cause when a member searches?
