### ISSUE TITLE
Find and View Spend Activities Feature

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/tempo#616]
_Add it here:_

__Is this part of a User Journey?__

_As a member or earn group I can search and filter earn groups_

---

### Acceptance Criteria:

**General**
- [x] Filter activities by nearby and online (online activities will still show in nearby if it's spend venue has an address - @JonnyBuck16 @harrietepugh  can you confirm that is right please?
- [x] Filter based on location 
- [x] Filter by activity type (select one at a time) 
- [x] Back end query to fetch all spend activities where the spend venue has marked themselves as public AND the spend activity has been marked as public 
- [x] Update back end query to fetch details for specific spend activity
- [x] Update back end query to fetch details for specific spend venue
- [x] Make sure you can view all pages even if not logged in

**Comment by JonnyBuck16** [comment]
Correct @thejoefriel - thanks for double-checking
