### ISSUE TITLE
Update Tags & Tabs

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/tempo#628]
**UPDATE**
- [x] Tag / unclickable - @jema28 can you explain what the difference is for this component? It seems to be the same as for release 1?

**NEW**
- [x] Tag (clickable) - selected & unselected
- [x] Tab Small
- [x] Tab Large

**Comment by jema28** [comment]
Hey @thejoefriel, I double-checked the tag, the text has been bumped up from 12px to 14px so it's more accessible.
