### ISSUE TITLE
If I have over 20 records, I can select Load More to load the next 20 records

### ISSUE THREAD

**Issue by JonnyBuck16** [yalla-coop/tempo#71]
__Is there an associated User Story?__

#69  #70  

__Is this part of a User Journey?__

#68 

### Acceptance Criteria:
- [ ] Total list of records
- [ ] Load More button
- [ ] Load more button loads another 20 records
- [ ] Back button
- [ ] Bonus: I can search/filter by activity name or partner name

**Comment by thejoefriel** [comment]
Have covered this in the acceptance criteria of #70 so will close this issue
