### ISSUE TITLE
I can view details for an individual transaction

### ISSUE THREAD

**Issue by JonnyBuck16** [yalla-coop/tempo#72]
__Is there an associated User Story?__

If I click on a transaction, I am able to see more information, including the transaction date, the activity date (if filled in), Member Name, the activity name (if filled in) the number of Time Credits given out, and a gifted or received label.

#69 #70 #71

__Is this part of a User Journey?__

#68 

---

### Acceptance Criteria:
- [ ] Follow wireframe **Transaction - individual earned**

**Comment by thejoefriel** [comment]
@jema28 hooking you into this issue so you know what needs to go into the wireframe
