### ISSUE TITLE
Incorrect Links and Routing

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/tempo#737]
- [x]  /earn-groups/:id (member)
website link directs me to twitter instead to web URL:
[https://www.loom.com/share/16955e36df664281b8a05e929e600f0a](https://www.loom.com/share/16955e36df664281b8a05e929e600f0a)

- [x] /earn-groups/volunteer/:id (member)
Go back button should direct to /earn not to members/earn
[https://www.loom.com/share/16e7ee6ccd0d4c08bbca4b35e70fdd9a](https://www.loom.com/share/16e7ee6ccd0d4c08bbca4b35e70fdd9a)

- [x] /spend-venue/:id (member)
Website link directs me back to app
[https://www.loom.com/share/1b70a9f302ac4984a120b2a0f4a4f690](https://www.loom.com/share/1b70a9f302ac4984a120b2a0f4a4f690)

- [x] /admin/earn-groups/:id
clicking on spend activity record directs ti wrong URL: /admin/spend-venue/undefined/details (not sure if bug)

- [x]  /admin/spend/3/edit 
Link should be called **View Spend Venue**
![https://s3-us-west-2.amazonaws.com/secure.notion-static.com/804d3829-11d3-470f-bbce-dbdb8ee71934/Bildschirmfoto_2020-07-13_um_17.02.13.png](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/804d3829-11d3-470f-bbce-dbdb8ee71934/Bildschirmfoto_2020-07-13_um_17.02.13.png)

**Comment by fadeomar** [comment]
` /earn-groups/volunteer/:id (member)` this point solved in PR #764

**Comment by fadeomar** [comment]
this is not a bug: the record there is a static one doesn't come from the back end yet
