### ISSUE TITLE
Spend Venue Insights not working

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/tempo#738]
/spend-venue/insights (spend venue)

it says "no records" in transactions table although I have accepted 4 TCs and 3 records → the csv download for it works!

![https://s3-us-west-2.amazonaws.com/secure.notion-static.com/d778d787-b6fb-410a-a807-2b7a0593c111/Bildschirmfoto_2020-07-13_um_16.34.35.png](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/d778d787-b6fb-410a-a807-2b7a0593c111/Bildschirmfoto_2020-07-13_um_16.34.35.png)

**Comment by ashatat** [comment]
@thejoefriel  is this still happening? there was a bug on table component that Ramy fixed yesterday
