### ISSUE TITLE
Programme Export Bugs

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/tempo#752]
**Earn Groups**
- [ ] Region isn't being exported, but checking the database we do have region (London) for Movers and Shakers
- [ ] Joining date should just be the date (remove the time)

**Transactions**
- [ ] Activity description (earn) is exporting the earn group description but instead it should be what they put (if anything) as the activity name in this input here (e.g. coffee club): http://www.clipular.com/posts/4709983181340672?k=o1tINehNJTfcjMotvWhiLwDzupE

**Comment by ashatat** [comment]
@thejoefriel  I believe this was fixed in https://github.com/yalla-coop/tempo/pull/730
