### ISSUE TITLE
Decide what data we need to put on the production version we give Tempo to test

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/tempo#778]
My initial thoughts are simply:

- [ ] 2 x Staff log in accounts (so they can test it shows the right user who carried out the transaction)
- [ ] 1 x Earn group not affiliated with any programme
    - [ ] 1 x live spend activity for this earn group
- [ ] 1 x Spend venue 
    - [ ] 1 x live spend activity for this spend venue

I think we have 0 programmes, 0 members and 0 transactions. 

@RamyAlshurafa what do you think?

**Comment by RamyAlshurafa** [comment]
@thejoefriel 
i think we just should try to simulate how it will work on production, so just seed the data they can't add(spend partners & tempo staff) otherwise they can initiate them manually

**Comment by RamyAlshurafa** [comment]
so super admin user + admin user + 1 spend partner
