### ISSUE TITLE
Make sure all emails are working

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/tempo#794]
Double check all emails and make sure they are working as they should 

https://github.com/yalla-coop/tempo/issues/181

**Comment by thejoefriel** [comment]
The main thing on this one @MohammedYehia @RamyAlshurafa is to also double check that when staff send a message as part of approving / partially approving / rejecting credit requests, that the message is contained in the email too :)

**Comment by ashatat** [comment]
@thejoefriel  && @MohammedYehia   should email be sent to the earngroup when the admin issue timecredits outside of approving/partially approving a credit requests?

**Comment by thejoefriel** [comment]
They should get an email if the credit request has been rejected.

Regarding issuing, I need @harrietepugh @JonnyBuck16 to confirm as they never provided us copy for this, but yeah does seem weird since they can write a message when issuing credits

**Comment by JonnyBuck16** [comment]
This is in issue #181
