### ISSUE TITLE
Data Issues

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/tempo#841]
- [x] Tempo Individual Programmes Page - Spend Venues stat is counting earn groups where members have spent credits. Should only count Spend Venues. So in this example, a member has spent with an earn group and with a spend venue so the stat should show 1 Spend Venue: http://www.clipular.com/posts/6457689797033984?k=YC_TjPTXVilLm3-indOJnjfErC4

- [ ] Tempo Earn Groups Page 
    - [x]  Total Members stat is counting inactive members in earn groups (not just active members in earn groups). In this example you can seen in the table there are no active members but in the stat it still shows 1: http://www.clipular.com/posts/5809978127155200?k=8Im3nKts6VWUOy7p683K5RzRH9g
    - [x] Spend % isn't calculating correctly in table. In this example 6 of 10 TCs given out have been spent (4 were spent directly, 2 were gifted and then spent) so the spend % should be 60%. You can see here in the individual earn group page it is correct http://www.clipular.com/posts/5386517470773248?k=KCuMZnHoDF5FO37q-CMKnibEKzg BUT in the table it shows 100% http://www.clipular.com/posts/6722406079791104?k=bUXI5DcH4jpCquuLKCHm6v7nnQA
After more transactions I've noticed this spend % is going over 100, so there's clearly something wrong

- [x] Tempo Individual Earn Group Page 
    - [x] Spend % isn't calculating correctly in Members table. In this example, you can see on the Member's page they have spent 100%, http://www.clipular.com/posts/5975548579545088?k=sOXs3ZcsGzWhe9pqZJUKnHwBVeM BUT here it shows them as spending 102% http://www.clipular.com/posts/4944922355171328?k=MVcvcCTY64tT7eAbP4BySL-M27I
They did spend 2 that were gifted to them which another member had earned with that earn group so maybe that is making this query incorrect

- [x] Tempo Members Page - please remove the Programmes column

- [x] Tempo Programmes and Individual Programmes - Members Reached stat should be  any member who has received (gifted or earned) Time Credits linked to that programme AND all current active volunteers (i.e. not including those removed) for Earn Groups currently part of the programme (i.e. not including earn groups no longer active in the programme). Make sure as well that all members are unique, so if a member has received TCs linked to that programme and volunteer for an earn group they are not counted twice

- [x] Exporting Spend Venues from Programmes throws a Network error

**Comment by dupreesi** [comment]
new data script (hopefully without errors)
[Data Testing Plan.docx](https://github.com/yalla-coop/tempo/files/4946620/Data.Testing.Plan.docx)
