### ISSUE TITLE
Counter Input issue when typing (Spend TC by Access Code)

### ISSUE THREAD

**Issue by dupreesi** [yalla-coop/tempo#860]
The counter input doesn't update correctly when using the keyboard
-> The Time Credit Calculator gets confused when I type over a field that was previously too big

--

video: https://we.tl/t-mHSe0W8LHY

**Comment by fadeomar** [comment]
http://localhost:3000/spend/1/spend-time-credits as a member

**Comment by RamyAlshurafa** [comment]
http://localhost:3000/admin/issue-credits/earn-groups/3
