### ISSUE TITLE
Render user message when no spend TC options for activity available

### ISSUE THREAD

**Issue by dupreesi** [yalla-coop/tempo#862]
when there are no spend option for a acitvity (e.g. when all online codes are used and users cannot book anymore) render a message on the page: "At the moment there are no options to spend Time Credits for this activity. Please come back soon".

--

video: https://we.tl/t-7FI3GoXHTY

**Comment by thejoefriel** [comment]
Hey  @fadeomar  sorry, while this is definitely a nice back up, we also need to ensure the following:

- [ ] If the only option for a spend activity is booking codes and there are none available then do not show in the Spend search section (or the dashboard section) 

Do you mind looking at that as part of your PR please?

**Comment by RamyAlshurafa** [comment]
@thejoefriel could you open a new issue for this, as it might require backend modification
