### ISSUE TITLE
Admin: Spend Venue details are not shown sometimes

### ISSUE THREAD

**Issue by dupreesi** [yalla-coop/tempo#863]
even thoug the profile data renders correctly on the admin dashboard it sometimes shows N/A for fields. 
please make sure the loading / get request works as expected. 

video: https://we.tl/t-hBFVsdZZDd

**Comment by fadeomar** [comment]
what the timestamp for this bug because it may be issue with the server we will open the log to see what was the cause

**Comment by dupreesi** [comment]
@fadeomar yesterday at 12:54

**Comment by dupreesi** [comment]
can't replicate this
