### ISSUE TITLE
As an Earn Group I can add/invite a Volunteer 

### ISSUE THREAD

**Issue by JonnyBuck16** [yalla-coop/tempo#88]
__Is there an associated User Story?__

#86 #87 

__Is this part of a User Journey?__

#85 
---

### Acceptance Criteria:
- [ ] Explanation of how to add Volunteers
- [ ] Unique invite link for the Earn Group (this is the same link they give to all potential members)
- [ ] Copy Link button
- [ ] Button and details to add someone without an email #122

**Comment by thejoefriel** [comment]
**NOTE: Front end of this has now been done**
