### ISSUE TITLE
Double Space in the text input fields "type  here"

### ISSUE THREAD

**Issue by dupreesi** [yalla-coop/tempo#883]
https://time-credits-tempo.herokuapp.com/earn-groups/sign-up
-> remove double space from placeholder
![Bug 64](https://user-images.githubusercontent.com/23721486/88040340-0d098400-cb49-11ea-96f3-17fc707270d6.png)

**Comment by fadeomar** [comment]
this is weird I've checked it in my div tools and looks fine can you check it again  plz
