### ISSUE TITLE
Booking Code -> don't allow to input empty codes 

### ISSUE THREAD

**Issue by dupreesi** [yalla-coop/tempo#884]
https://time-credits-tempo.herokuapp.com/admin/spend-venue/37/create-spend-activity
The way   the box detects codes seems to be a little odd. It will say it's detected one   if you put a comma after a code, even if you haven't written the next code?   So if you left it blank, what code does it think exists? 

-> add validation so no empty codes are being detected
 
video: https://we.tl/t-9VKJkQWTKI

**Comment by thejoefriel** [comment]
Still not working
