### ISSUE TITLE
I click copy on the link (and send to volunteers manually)

### ISSUE THREAD

**Issue by JonnyBuck16** [yalla-coop/tempo#89]
__Is there an associated User Story?__

#86 #87 #88 

__Is this part of a User Journey?__

#85 

---

### Acceptance Criteria:
- [ ] Small url link 
- [ ] Copy button 
- [ ] Message to say it has been copied when I click 
- [ ] Bonus: Option to share by email, Facebook or whatsapp
- [ ] Bonus: Generates template message for them

**Comment by thejoefriel** [comment]
This is covered in #88 so closing this issue
