### ISSUE TITLE
Can't put in website, facebook, twitter on edit earn group profile form

### ISSUE THREAD

**Issue by dupreesi** [yalla-coop/tempo#893]
https://time-credits-tempo.herokuapp.com/earn-groups/5/profile/edit

The form   says the website url is not valid whatever I try and it is not pulling   through the facbook or twitter links

videos: https://we.tl/t-0DSdiQ3Ohi

**Comment by thejoefriel** [comment]
Reopening as still not fixed:

Tempo: Partly fixed. Website is fine but Twitter and Facebook still don't seem to pull through. I went back to the edit page after having entered a Facebook and Twitter, and both boxes had just been cleared blank.
