### ISSUE TITLE
The 'View profile' button is missing from the earn group listing once I have made it public

### ISSUE THREAD

**Issue by dupreesi** [yalla-coop/tempo#896]
https://time-credits-tempo.herokuapp.com/earn-groups/5/profile/edit

Add button 'View Profile' on earn groups profile edit page 

video: https://we.tl/t-23zitzBudI

**Comment by thejoefriel** [comment]
Re-opening. It does work but they've said it only shows when you manually refresh the page. Need to check this

**Comment by thejoefriel** [comment]
Closing as we can't replicate: https://www.loom.com/share/4bb92b28e4d942a4b6c526c3ddf70533
