### ISSUE TITLE
Spend Activity details doesn't render properly in member transaction list

### ISSUE THREAD

**Issue by dupreesi** [yalla-coop/tempo#898]
https://time-credits-tempo.herokuapp.com/earn-groups/members/kcunju78

Spend activitiy details are not pulling through to the transactions on individual   member pages (spend activity with my earn group). They are listed on the   overall transaction record but not on the member transaction list.

video: https://we.tl/t-xyUGxqzrWB

**Comment by thejoefriel** [comment]
This still isn't working so I'm re-opening the issue:
https://www.loom.com/share/5fc6f41ead184a73937d32f4febc9e05
