### ISSUE TITLE
I click to add myself as volunteer

### ISSUE THREAD

**Issue by JonnyBuck16** [yalla-coop/tempo#90]
__Is there an associated User Story?__
#86 #87 #88 

__Is this part of a User Journey?__

#85

**Comment by thejoefriel** [comment]
@JonnyBuck16 @harrietepugh - sorry, I noticed we currently don't have this in the wireframes? Is this something we still want?

**Comment by harrietepugh** [comment]
Up to you Jonny as it will impact on the Customer platform. What would be the current flow be for a Customer that wanted to sign up as a Member? My instinct is to minimise all these little bits that make it busier/more complicated if there is another straightforward way of doing it

**Comment by JonnyBuck16** [comment]
I don't think we need it. All they would have to do is fill in the form on the magic URL themselves - assuming this wouldn't cause an issue if they used the same email address @thejoefriel to do this?

**Comment by thejoefriel** [comment]
Yeah that would be absolutely fine @JonnyBuck16 :) Cool, ok I'll close this issue
