### ISSUE TITLE
In the all Earn groups export, the active members is 26, when on the dashboard in the tool, it states 25

### ISSUE THREAD

**Issue by dupreesi** [yalla-coop/tempo#901]
make sure numbers are correct..

video: https://we.tl/t-POkby69Vpb

**Comment by RamyAlshurafa** [comment]
Hey @dupreesi @JonnyBuck16 
this is not a bug, the stats show the number of unique members, and in the CSV each row shows the members of the earn group, so there are some members are in multiple earn group
@ashatat has connected to production DB and double-checked
