### ISSUE TITLE
Register with link from group (demographics) -> make sure validation works for DOB input

### ISSUE THREAD

**Issue by dupreesi** [yalla-coop/tempo#903]
http://time-credits-tempo.herokuapp.com/continue-sign-up

make sure when clicking submit that validation works for all inputs (especially DOB)

Registration link generated from group; when opened and completed, on the second page asking demographics questions it doesn't allow the continue button to be clicked but doesn’t say what the issue is until the date of birth field is   edited, then it shows an error message.

![bug 106](https://user-images.githubusercontent.com/23721486/88052864-34694c80-cb5b-11ea-9cb4-9d1c58408991.jpg)

**Comment by RamyAlshurafa** [comment]
can't replicate this
