### ISSUE TITLE
spinning loading circles underneath earn activities 

### ISSUE THREAD

**Issue by dupreesi** [yalla-coop/tempo#905]
http://time-credits-tempo.herokuapp.com/earn-groups/members/kculjow7
http://time-credits-tempo.herokuapp.com/members/dashboard

There are loading circles spinning under some of the earn activities which never load anything/stop spinning.
happens also on mobile

time stamp: 21.07.2020 at 10:40

video: https://we.tl/t-wCYZNLeMFK

**Comment by thejoefriel** [comment]
Re-opening this because it still seems to happen

https://www.loom.com/share/a14ff703ba3f415eb877458211f79e42
