### ISSUE TITLE
I am able to remove the 2nd, 3rd, etc specific roles, but not the first one? 

### ISSUE THREAD

**Issue by dupreesi** [yalla-coop/tempo#915]
https://time-credits-tempo.herokuapp.com/admin/earn-groups/10/edit

![Bug 124](https://user-images.githubusercontent.com/23721486/88075546-3c37e980-cb79-11ea-9129-7ac04c7637f9.jpg)

**Comment by fadeomar** [comment]
we agreed to not add the remove button on the first one, and it holds the optional flag, but if they consist to be a bug what is your scenario if we remove the first role, should hide all the section or convert ` + add another activity` to  ` + add an activity`?
@thejoefriel @dupreesi

**Comment by thejoefriel** [comment]
You shouldn't be able to move the first one (as it's always there when you first load the form) and you can just delete the inputs on the first one. Can you check please @fadeomar  that if you delete the inputs from the first one and hit save that these are removed? I'll then flag with Tempo that this is how it should be working
