### ISSUE TITLE
changing one field (first name) and clicking save changes causes a blank phone number field to suddenly become compulsory

### ISSUE THREAD

**Issue by dupreesi** [yalla-coop/tempo#917]
https://time-credits-tempo.herokuapp.com/settings

![bug 127](https://user-images.githubusercontent.com/23721486/88077312-6ee2e180-cb7b-11ea-8325-4034908b7916.png)

**Comment by fadeomar** [comment]
please double-check this issue, I've tried many times but the bug doesn't appear with me

**Comment by RamyAlshurafa** [comment]
it's maybe something with the browser autofill

**Comment by dupreesi** [comment]
this is slightly confusing: Account settings are using the contact_number field from earn_groups_profiles which is an optional field (rather than phone_number from credentials). But on the settings page it is required (which might be better anyway). 
so for now I would say we make it an optional field
