### ISSUE TITLE
create spend activity button loading spinner doesn't stop spinning

### ISSUE THREAD

**Issue by dupreesi** [yalla-coop/tempo#924]
https://time-credits-tempo.herokuapp.com/admin/spend-venue/52/create-spend-activity

I   clicked to create the activity and a spinning wheel on thecreate activity   button appears infinitely - at time of writing it has been spinning for at   least 3 minutes

![Bug 139](https://user-images.githubusercontent.com/23721486/88080025-cb93cb80-cb7e-11ea-8c30-37a5bc42861f.jpg)

video: https://we.tl/t-gZkRJC75fc

**Comment by dupreesi** [comment]
cannot replicate so will close

**Comment by thejoefriel** [comment]
Reopneing as not fixed everywhere by the looks of it : https://www.loom.com/share/a14ff703ba3f415eb877458211f79e42

They said it was working then stopped, so not sure if a caching issue
