### ISSUE TITLE
No usage of back button when viewing spend activity

### ISSUE THREAD

**Issue by dupreesi** [yalla-coop/tempo#927]
https://time-credits-tempo.herokuapp.com/spend/27

When I 'View Spend Activity' via the link on the Earn Activity page, it opens in a new window so I can't then use the Back Button displayed on the Spend Activity page. 

-> open activity on same tab

video: https://we.tl/t-VVI5ZIVasE

**Comment by thejoefriel** [comment]
As discussed with @harrietepugh  @JonnyBuck16  - we have agreed it should still open on a new tab, but we will update the go back button so if there is no page to go back to (i.e. a new tab) , it will take them to /earn (for earn group listings) and /spend (for spend activity/partner listings)
