### ISSUE TITLE
Product Handover - Agree Time

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/tempo#96]
Morning @laurajtempo hope you had a great weekend!
As you can hopefully get a sense, looking at the project plan, we're in a good place and all on track to deliver the product as planned by 15th. Is there a time on Friday that works best to meet? I also think we may be able to hand over on 14th as well if that is more useful.

**Comment by laurajtempo** [comment]
Would end of the day on Thursday work? I'm free any time from 3.15, or if not, on Friday at 10.30 or 11.30?

**Comment by thejoefriel** [comment]
Hi @laurajtempo  end of day on Thursday sounds great - say 5?

**Comment by laurajtempo** [comment]
@thejoefriel  that works for me - our new address is Studio 301,138-146 Cambridge Heath Road, E1 5QJ if you want to come here? It's 2 minutes down the road from where we were before

**Comment by thejoefriel** [comment]
@laurajtempo - perfect. I'll send you a calendar invite now
