### ISSUE TITLE
Users - Provide information

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/tempo#97]
Hi @laurajtempo are you able to supply the email address and full name for each of the users for this MVP please? We can then make sure they are added to the database prior to product handover. 

- 1 x Tempo 
- 1 x Charity
- 1 x Spend Partner
- 5 x Volunteers (who volunteer for the charity and would use their credits with the spend partner)

**Comment by laurajtempo** [comment]
Hi Joe, I was at Haringey Shine yesterday, who have agreed to help us with this next week. I'm still waiting for the volunteer details, and the correct details for the Spend partner, who I'm calling today to chase - hopefully I can send it all over Thursday morning, Shine are just trying to confirm the volunteers tat can be available on Monday, will keep you updated!

**Comment by laurajtempo** [comment]
Hi Joe I’ve got the volunteer details now and forwarded them - we also had one other volunteer who doesn’t have an email address and doesn’t have a working phone at the moment-  but would like to get involved. He has earned Time Credits before.

His volunteer manager offered to set up an email for him, is there any way we can give an email address for him in the interim so he can still get involved? We could create an email on gmail if so and I could get you details tomorrow morning?

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by thejoefriel** [comment]
Hi @laurajtempo thanks for this! Once we get the charity and spend partner, we'll upload all of them together. In terms of tempo, would it be your own email address?

Regarding the extra volunteer, yes you can just create a gmail account for them. To be honest, the email is only used as a unique way to identify them for logging in so any made up email address will do as well.

**Comment by laurajtempo** [comment]
Yep, me for Tempo is fine for now, and I'll get the other ones over to you as soon as I can.
